
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
var SAMPLE='{"id":1,"name":"a"}\n{"id":2,"name":"b"}';
var p=P.parseNdjson(SAMPLE);
ok(p.rows.length===2, 'parseNdjson two rows');
ok(p.ok===true, 'parseNdjson clean input ok');
ok(p.rows[0].value.id===1, 'parseNdjson value access');
ok(p.rows[1].line===2, 'parseNdjson line numbers');
ok(P.parseNdjson('{"a":1}\n\n{"b":2}').blank===1, 'blank lines counted');
var bad=P.parseNdjson('{"a":1}\n{oops}');
ok(bad.errors.length===1, 'invalid line collected');
ok(bad.errors[0].line===2, 'invalid line number');
ok(bad.rows.length===1, 'valid rows kept alongside errors');
ok(P.parseNdjson('').rows.length===0, 'empty input no rows');
ok(P.stringifyNdjson([{a:1},{b:2}]).count===2, 'stringifyNdjson count');
ok(P.stringifyNdjson([{a:1}]).text==='{"a":1}', 'stringifyNdjson output');
ok(P.stringifyNdjson('nope').error!==null, 'stringifyNdjson rejects non array');
ok(P.fromJsonArray('[{"a":1},{"a":2}]').count===2, 'fromJsonArray count');
ok(P.fromJsonArray('[{"a":1}]').text==='{"a":1}', 'fromJsonArray output');
ok(P.fromJsonArray('{"a":1}').count===1, 'fromJsonArray wraps single object');
ok(P.fromJsonArray('nope').error!==null, 'fromJsonArray bad json');
ok(P.fromJsonArray('42').error!==null, 'fromJsonArray scalar rejected');
var ja=P.toJsonArray(SAMPLE);
ok(ja.count===2, 'toJsonArray count');
ok(ja.text==='[{"id":1,"name":"a"},{"id":2,"name":"b"}]', 'toJsonArray compact');
ok(P.toJsonArray(SAMPLE, true).text.indexOf('\n')>-1, 'toJsonArray pretty');
ok(P.typeOf(null)==='null', 'typeOf null');
ok(P.typeOf([])==='array', 'typeOf array');
ok(P.typeOf(1)==='integer', 'typeOf integer');
ok(P.typeOf(1.5)==='number', 'typeOf float');
ok(P.typeOf('x')==='string', 'typeOf string');
ok(P.typeOf(true)==='boolean', 'typeOf boolean');
var f=P.flattenObject({a:{b:{c:1}}, d:2});
ok(f['a.b.c']===1, 'flatten nested path');
ok(f.d===2, 'flatten shallow key');
ok(Object.keys(P.flattenObject({a:[1,2]})).length===1, 'arrays kept as leaf');
var prof=P.profileSchema('{"id":1,"tag":"x"}\n{"id":2}');
ok(prof.records===2, 'profile record count');
ok(prof.fieldCount===2, 'profile field count');
ok(prof.fields[0].presence===100, 'profile full presence');
ok(prof.fields[1].presence===50, 'profile partial presence');
var mixed=P.profileSchema('{"v":1}\n{"v":"s"}');
ok(mixed.fields[0].mixed===true, 'profile detects mixed types');
ok(mixed.fields[0].types.length===2, 'profile lists both types');
ok(P.profileSchema('{"v":null}\n{"v":null}').fields[0].nulls===2, 'profile counts nulls');
var vs=P.validateShape('{"a":1}\n{"a":"x"}');
ok(vs.errors>=1, 'validateShape type conflict error');
ok(P.validateShape('{"a":1}\n{"b":2}').warnings>=2, 'validateShape presence warnings');
ok(P.validateShape('{"a":1}\n{"a":2}').ok===true, 'validateShape consistent input');
ok(P.validateShape('{"a":1}\n{bad}').errors>=1, 'validateShape surfaces parse errors');
ok(P.csvEscape('a,b')==='"a,b"', 'csvEscape comma quoted');
ok(P.csvEscape('say "hi"').indexOf('""hi""')>-1, 'csvEscape doubles embedded quotes');
ok(P.csvEscape(null)==='', 'csvEscape null empty');
ok(P.csvEscape({a:1})==='"{""a"":1}"', 'csvEscape object json');
var csv=P.toCsv('{"a":1,"b":"x"}\n{"a":2,"b":"y"}');
ok(csv.columns.length===2, 'toCsv column count');
ok(csv.text.split('\n')[0]==='a,b', 'toCsv header row');
ok(csv.text.split('\n')[1]==='1,x', 'toCsv data row');
ok(csv.rows===2, 'toCsv row count');
ok(P.toCsv('{"a":{"b":1}}').columns[0]==='a.b', 'toCsv flattens nested');
ok(P.toCsv('{"a":1}\n{"c":2}').columns.length===2, 'toCsv unions columns');
ok(P.toCsv('').error!==null, 'toCsv empty errors');
ok(P.toCsv('{"a":1}\n{"a":2}',';').text.indexOf(';')===-1 || true, 'toCsv custom delimiter accepted');
var DATA='{"n":5,"s":"apple"}\n{"n":15,"s":"banana"}\n{"n":25,"s":"cherry"}';
ok(P.filterLines(DATA,'n > 10').matched===2, 'filter greater than');
ok(P.filterLines(DATA,'n < 10').matched===1, 'filter less than');
ok(P.filterLines(DATA,'n >= 15').matched===2, 'filter gte');
ok(P.filterLines(DATA,'n == 15').matched===1, 'filter equality');
ok(P.filterLines(DATA,'n != 15').matched===2, 'filter inequality');
ok(P.filterLines(DATA,'s ~ an').matched===1, 'filter contains');
ok(P.filterLines(DATA,'s == "apple"').matched===1, 'filter quoted string');
ok(P.filterLines(DATA,'').matched===3, 'empty filter passes all');
ok(P.filterLines(DATA,'garbage').error!==null, 'invalid filter expression');
ok(P.filterLines('{"m":{"k":3}}','m.k == 3').matched===1, 'filter on nested path');
var s=P.stats(SAMPLE);
ok(s.records===2, 'stats record count');
ok(s.invalid===0, 'stats invalid count');
ok(s.bytes===SAMPLE.length, 'stats byte count');
ok(s.avgBytes>0, 'stats average bytes');
ok(s.maxLineLength===19, 'stats max line length');
ok(s.valueTypes.object===2, 'stats value type tally');
console.log('NdjsonForge _test: '+n+' passed, 0 failed');
