
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
ok(P.fmScalar('42')===42 && P.fmScalar('-1.5')===-1.5,'scalar number');
ok(P.fmScalar('true')===true && P.fmScalar('false')===false,'scalar bool');
ok(P.fmScalar('null')===null && P.fmScalar('~')===null,'scalar null');
ok(P.fmScalar('"a: b"')==='a: b',"scalar quoted");
ok(Array.isArray(P.fmScalar('[a, b]')) && P.fmScalar('[a, b]').length===2,'scalar inline array');
ok(P.fmScalar('[]').length===0,'scalar empty array');
ok(P.fmSplit('no fm').has===false,'split none');
ok(P.fmSplit('---\na: 1\n---\nbody').has===true,'split has');
ok(P.fmSplit('---\na: 1\n---\nbody').body==='body','split body');
const r=P.fmParse('---\ntitle: hi\ndraft: false\ntags: [a, b]\n---\nbody text');
ok(r.error===null && r.has===true,'parse ok');
ok(r.data.title==='hi' && r.data.draft===false,'parse values');
ok(r.data.tags.length===2 && r.data.tags[0]==='a','parse inline list');
ok(r.order.join(',')==='title,draft,tags','parse order');
const bl=P.fmParse('---\ntags:\n  - x\n  - y\n---\n');
ok(bl.data.tags.length===2 && bl.data.tags[1]==='y','block list');
ok(P.fmParse('---\n# comment\na: 1\n---\n').data.a===1,'comment skipped');
ok(P.fmParse('---\nnot valid line\n---\n').error!==null,'bad line error');
ok(P.fmParse('plain').has===false,'no fm parse');
ok(P.fmParse(null).body==='','null safe');
ok(P.fmParse('---\na: 1\na: 2\n---\n').dup.length===1,'duplicate key');
ok(P.fmDump('a: b')==='"a: b"','dump quoting');
ok(P.fmDump(['x','y'])==='[x, y]','dump array');
ok(P.fmDump(null)==='null' && P.fmDump(3)==='3','dump primitives');
const out=P.fmStringify(r.data, r.order, r.body);
ok(out.indexOf('---\ntitle: hi')===0,'stringify head');
ok(P.fmParse(out).data.tags.length===2,'stringify roundtrip');
ok(P.fmLint(P.fmParse('plain'))[0].level==='error','lint missing block');
ok(P.fmLint(r,['title']).length===0,'lint pass');
ok(P.fmLint(r,['author'])[0].msg.indexOf('author')>0,'lint missing field');
ok(P.fmLint(P.fmParse('---\ntitle: '+'x'.repeat(70)+'\n---\n'),[]).length===1,'lint long title');
console.log('PASS '+n+' assertions');
