
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const kernel=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1])[0];
const mo={exports:{}};new Function('module','exports',kernel)(mo,mo.exports);
const C=mo.exports;let pass=0,fail=0;
function ok(n,c){if(c)pass++;else{fail++;console.error('FAIL '+n);}}
ok('presets', C.PRESETS.length>=10);
ok('base', C.baseName('/a/b/c.mp4')==='c');
ok('base-noext', C.baseName('movie')==='movie');
ok('quote', C.quote('a b')==='"a b"'&&C.quote('ab')==='ab');
var r=C.build({input:'in.mp4',vcodec:'libx264',crf:'23',preset:'medium',acodec:'aac',abitrate:'128k'});
ok('build-ok', !r.error);
ok('build-y', r.value.cmd.indexOf('ffmpeg -y ')===0);
ok('build-i', r.value.cmd.indexOf('-i in.mp4')>=0);
ok('build-crf', r.value.cmd.indexOf('-crf 23')>=0);
ok('build-out', /in_out\.mp4$/.test(r.value.cmd));
var r2=C.build({input:'a.mkv',gif:true,fps:'12',scale:'480'});
ok('gif-palette', r2.value.cmd.indexOf('palettegen')>=0);
ok('gif-ext', /a\.gif$/.test(r2.value.cmd));
var r3=C.build({input:'a.mp4',novideo:true,acodec:'libmp3lame',abitrate:'192k',ext:'mp3'});
ok('audio-vn', r3.value.cmd.indexOf('-vn')>=0);
ok('audio-ext', /a_out\.mp3$/.test(r3.value.cmd));
var r4=C.build({input:'a.mp4',vcodec:'copy',acodec:'copy',start:'00:00:10',duration:'00:00:30'});
ok('cut-ss', r4.value.cmd.indexOf('-ss 00:00:10')<r4.value.cmd.indexOf('-i '));
ok('cut-t', r4.value.cmd.indexOf('-t 00:00:30')>=0);
ok('cut-note', r4.value.notes.join('|').indexOf('关键帧')>=0);
var r5=C.build({input:'a.mp4',vcodec:'libx265',crf:'28',tag:'hvc1'});
ok('h265-tag', r5.value.cmd.indexOf('-tag:v hvc1')>=0);
ok('h265-note', r5.value.notes.join('|').indexOf('hvc1')>=0);
var r6=C.build({input:'a.mp4',vcodec:'copy',mute:true});
ok('mute', r6.value.cmd.indexOf('-an')>=0);
var r7=C.build({input:'a.mp4',frames:true,fps:'1'});
ok('frames', /frame_%04d\.jpg$/.test(r7.value.cmd));
var r8=C.build({input:'a.mp4',vcodec:'libx264',crf:'23',scale:'1280'});
ok('scale', r8.value.cmd.indexOf('scale=1280:-2')>=0);
ok('empty-in', C.build({input:'  '}).error!=null);
ok('tok', C.tokenize('ffmpeg -i "a b.mp4" out.mp4').length===4);
ok('tok-quote', C.tokenize('ffmpeg -i "a b.mp4" out.mp4')[2]==='a b.mp4');
var e=C.explain('ffmpeg -y -i in.mp4 -c:v libx264 -crf 23 out.mp4');
ok('exp-ok', !e.error);
ok('exp-inputs', e.value.inputs[0]==='in.mp4');
ok('exp-outputs', e.value.outputs[0]==='out.mp4');
ok('exp-crf', e.value.rows.some(function(x){return x.flag==='-crf'&&x.arg==='23';}));
ok('exp-cv', e.value.rows.some(function(x){return x.flag==='-c:v'&&/视频编码器/.test(x.desc);}));
ok('exp-faststart-warn', e.value.warn.join('|').indexOf('faststart')>=0);
var e2=C.explain('ffmpeg -i a.mp4 -c:v copy -vf scale=640:-2 b.mp4');
ok('exp-conflict', e2.value.warn.join('|').indexOf('冲突')>=0);
var e3=C.explain('ffmpeg -c:v libx264');
ok('exp-noinput', e3.value.warn.join('|').indexOf('-i')>=0);
ok('exp-bad', C.explain('ls -la').error!=null);
ok('exp-empty', C.explain('').error!=null);
ok('exp-unknown', C.explain('ffmpeg -i a.mp4 -zzz 1 b.mp4').value.warn.join('|').indexOf('未识别')>=0);
console.log((fail?'FAIL':'PASS')+' FfmpegForge '+pass+'/'+fail);process.exit(fail?1:0);
