const { JSDOM } = require('C:/Users/53014/.workbuddy/binaries/node/workspace/node_modules/jsdom');
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true});
const {window}=dom; const errs=[]; window.addEventListener('error',e=>errs.push(e.message||String(e.error)));
setTimeout(()=>{ const doc=window.document; let pass=0,fail=0;
  const ok=(n,c)=>c?pass++:(fail++,console.error('  FAIL: '+n));
  ok('LifeForgePure exposed', typeof window.LifeForgePure==='object');
  ok('step btn', !!doc.getElementById('step'));
  doc.getElementById('step').click();
  ok('svg rendered', doc.getElementById('out').innerHTML.indexOf('<svg')>-1);
  ok('no js errors', errs.length===0);
  console.log('LifeForge smoke: '+pass+' passed, '+fail+' failed');
  process.exit(fail?1:0);
}, 500);
