const { JSDOM } = require('C:/Users/53014/.workbuddy/binaries/node/workspace/node_modules/jsdom');
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true});
const {window}=dom; const errs=[]; window.addEventListener('error',e=>errs.push(e.message));
setTimeout(()=>{ const doc=window.document; let pass=0,fail=0;
  const ok=(n,c)=>c?pass++:(fail++,console.error('  FAIL: '+n));
  ok('SemverForgePure exposed', typeof window.SemverForgePure==='object');
  ok('check btn', !!doc.getElementById('check'));
  doc.getElementById('range').value='^1.2.3'; doc.getElementById('ver').value='1.2.5'; doc.getElementById('check').click();
  ok('output match', doc.getElementById('out').textContent.indexOf('匹配')>=0);
  doc.getElementById('ver').value='2.0.0'; doc.getElementById('check').click();
  ok('output no match', doc.getElementById('out').textContent.indexOf('不匹配')>=0);
  doc.getElementById('a').value='1.2.3'; doc.getElementById('b').value='1.2.4'; doc.getElementById('cmp').click();
  ok('compare output', doc.getElementById('out').textContent.indexOf('<')>=0);
  ok('no js errors', errs.length===0);
  if(errs.length) console.error('  js errors:',errs);
  console.log('SemverForge smoke: '+pass+' passed, '+fail+' failed');
  process.exit(fail?1:0);
},400);
