
const fs=require('fs'),path=require('path'),assert=require('assert');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=/<script>([\s\S]*?)<\/script>/.exec(html);
const mod={exports:{}};
new Function('module','exports','require', m[1])(mod,mod.exports,require);
const P=mod.exports;
let pass=0,fail=0;
function ok(c,msg){ if(c){pass++;} else {fail++; console.error('FAIL: '+msg);} }

ok(P.estimateTokens('')===0, 'empty prompt is zero tokens');
ok(P.estimateTokens('abcd')===1, 'four latin chars is one token');
ok(P.estimateTokens('\u4f60\u597d')===4, 'CJK weighted at 1.6 tokens per char');
ok(P.splitLines('a\nb').length===2, 'splitLines counts lines');
ok(P.splitLines('').length===0, 'empty text has no lines');
ok(P.splitLines('a\r\nb').length===2, 'CRLF normalized');
var d=P.diffLines('a\nb\nc','a\nx\nc');
ok(d.length===4, 'diff keeps same lines and both sides of change');
ok(d.filter(function(r){return r.type==='add';}).length===1, 'one added line');
ok(d.filter(function(r){return r.type==='del';}).length===1, 'one removed line');
ok(d.filter(function(r){return r.type==='same';}).length===2, 'two unchanged lines');
var same=P.diffLines('a\nb','a\nb');
ok(P.diffStats(same).changeRatio===0, 'identical text has zero change ratio');
ok(P.diffStats(same).same===2, 'stats count unchanged lines');
var st=P.diffStats(P.diffLines('a','b'));
ok(st.added===1 && st.removed===1, 'replacement counts as one add and one delete');
var wd=P.wordDiff('the quick fox','the slow fox');
ok(wd.filter(function(x){return x.type==='add';}).length===1, 'word diff detects one added word');
var t=P.tokenDelta('abcd','abcdabcd');
ok(t.before===1 && t.after===2, 'token delta before and after');
ok(t.delta===1, 'token delta value');
ok(t.pct===100, 'token delta percentage');
ok(P.tokenDelta('','abcd').pct===100, 'growth from empty reports 100 percent');
var c=P.costImpact('abcd','abcdabcd','gpt-4o-mini',1000,300);
ok(c.error===null, 'known model resolves');
ok(c.dailyAfter>c.dailyBefore, 'longer prompt costs more per day');
ok(c.monthlyDelta>0, 'monthly delta positive when prompt grows');
ok(Math.abs(c.monthlyDeltaCNY-c.monthlyDelta*7.2)<0.001, 'CNY conversion applied');
ok(P.costImpact('a','b','nope').error!==null, 'unknown model reports error');
ok(P.extractVars('{{a}} and {b} and ${c}').length===3, 'extract all three placeholder syntaxes');
ok(P.extractVars('{{x}} {{x}}').length===1, 'duplicate placeholders deduped');
var v=P.varDiff('{{a}} {{b}}','{{b}} {{c}}');
ok(v.added.length===1 && v.added[0]==='c', 'var diff detects added variable');
ok(v.removed.length===1 && v.removed[0]==='a', 'var diff detects removed variable');
ok(v.kept.length===1 && v.kept[0]==='b', 'var diff detects kept variable');
ok(v.breaking===true, 'variable signature change flagged as breaking');
ok(P.varDiff('{{a}}','{{a}}').breaking===false, 'identical variables not breaking');
var l=P.lintPrompt('');
ok(l.errors===1, 'empty prompt is an error');
ok(P.lintPrompt('use sk-abcdefghijklmnopqrst now').errors>=1, 'hardcoded secret flagged');
ok(P.lintPrompt('{{a}} {{b}').errors>=1, 'unbalanced placeholders flagged');
ok(P.lintPrompt('hello {{a}}').errors===0, 'clean short prompt has no errors');
var cmp=P.compare('a\nb','a\nc','gpt-4o-mini',10,10);
ok(cmp.stats.total===3, 'compare returns diff rows');
ok(cmp.cost.error===null, 'compare computes cost');
ok(typeof cmp.lintNew.tokens==='number', 'compare lints new version');

console.log(pass+' passed, '+fail+' failed');
process.exit(fail?1:0);
