const { JSDOM } = require('C:/Users/53014/.workbuddy/binaries/node/workspace/node_modules/jsdom');
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true});
const {window}=dom; const errs=[]; window.addEventListener('error',e=>errs.push(e.message||String(e.error)));
setTimeout(()=>{ const doc=window.document; let pass=0,fail=0;
  const ok=(n,c)=>c?pass++:(fail++,console.error('  FAIL: '+n));
  ok('ChangelogForgePure exposed', typeof window.ChangelogForgePure==='object');
  ok('gen btn', !!doc.getElementById('gen'));
  doc.getElementById('commits').value='feat: add X\nfix: kill bug'; doc.getElementById('cur').value='1.2.3'; doc.getElementById('gen').click();
  var out=doc.getElementById('out').textContent;
  ok('output produced', out.length>0 && out.indexOf('Features')>=0);
  ok('shows bump', out.indexOf('minor')>=0);
  ok('no js errors', errs.length===0);
  if(errs.length) console.error('  js errors:',errs);
  console.log('ChangelogForge smoke: '+pass+' passed, '+fail+' failed');
  process.exit(fail?1:0);
},500);
