
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const kernel=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1])[0];
const mo={exports:{}};new Function('module','exports',kernel)(mo,mo.exports);
const C=mo.exports;let pass=0,fail=0;
function ok(n,c){if(c)pass++;else{fail++;console.error('FAIL '+n+' got '+JSON.stringify(c));}}
ok('px1', C.px('16px')===16);
ok('px2', C.px('1rem')===16);
ok('tok4', C.spaceToken('16px')==='4');
ok('tok05', C.spaceToken('2px')==='0.5');
ok('tokpx', C.spaceToken('1px')==='px');
ok('tokbad', C.spaceToken('13px')===null);
ok('decl', C.parseDecls('a:1;b:2').length===2);
ok('decl-brace', C.parseDecls('.x{a:1}')[0][0]==='a');
var r=C.cssToTw('display:flex;padding:16px;margin-top:8px');
ok('css1', r.value.classes==='flex p-4 mt-2');
ok('css-color', C.cssToTw('color:#fff').value.classes==='text-white');
ok('css-bg', C.cssToTw('background-color:#5E6AD2').value.classes==='bg-[#5E6AD2]');
ok('css-arb', C.cssToTw('width:13px').value.classes==='w-[13px]');
ok('css-two', C.cssToTw('padding:16px 24px').value.classes==='py-4 px-6');
ok('css-fs', C.cssToTw('font-size:14px').value.classes==='text-sm');
ok('css-fw', C.cssToTw('font-weight:600').value.classes==='font-semibold');
ok('css-radius', C.cssToTw('border-radius:12px').value.classes==='rounded-xl');
ok('css-just', C.cssToTw('justify-content:space-between').value.classes==='justify-between');
ok('css-op', C.cssToTw('opacity:0.5').value.classes==='opacity-50');
ok('css-neg', C.cssToTw('margin-top:-8px').value.classes==='-mt-2');
ok('css-empty', C.cssToTw('').error!=null);
var t=C.twToCss('p-4');
ok('tw1', t.value.css==='padding: 1rem;');
ok('tw-flex', C.twToCss('flex items-center').value.css.indexOf('display: flex;')>=0);
ok('tw-items', C.twToCss('items-center').value.css==='align-items: center;');
ok('tw-arb', C.twToCss('text-[#abc]').value.css==='color: #abc;');
ok('tw-px', C.twToCss('px-6').value.css.indexOf('padding-left: 1.5rem;')>=0);
ok('tw-fs', C.twToCss('text-sm').value.css==='font-size: 14px;');
ok('tw-z', C.twToCss('z-10').value.css==='z-index: 10;');
ok('tw-op', C.twToCss('opacity-50').value.css==='opacity: 0.5;');
ok('tw-border', C.twToCss('border').value.css==='border-width: 1px;');
ok('tw-empty', C.twToCss('').error!=null);
ok('tw-unknown', C.twToCss('zzz-999').error!=null);
console.log((fail?'FAIL':'PASS')+' TwForge '+pass+'/'+fail);process.exit(fail?1:0);
