const { JSDOM } = require('C:/Users/53014/.workbuddy/binaries/node/workspace/node_modules/jsdom');
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true});
const {window}=dom; const errs=[]; window.addEventListener('error',e=>errs.push(e.message));
setTimeout(()=>{ const doc=window.document; let pass=0,fail=0;
  const ok=(n,c)=>c?pass++:(fail++,console.error('  FAIL: '+n));
  ok('DiffForgePure exposed', typeof window.DiffForgePure==='object');
  ok('run btn', !!doc.getElementById('run'));
  doc.getElementById('old').value='a\nb\nc'; doc.getElementById('new').value='a\nB\nc\nd'; doc.getElementById('run').click();
  const out=doc.getElementById('out').textContent||'';
  ok('output has plus', out.indexOf('+')>=0);
  ok('stat shown', (doc.getElementById('stat').textContent||'').indexOf('新增')>=0);
  doc.getElementById('mode').value='side'; doc.getElementById('run').click();
  ok('side table rendered', !!doc.querySelector('table.difftab'));
  ok('no js errors', errs.length===0);
  if(errs.length) console.error('  js errors:',errs);
  console.log('DiffForge smoke: '+pass+' passed, '+fail+' failed');
  process.exit(fail?1:0);
},400);
