
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
const good='v=DMARC1; p=quarantine; sp=reject; pct=100; rua=mailto:d@e.com; adkim=s;';
const st=P.dmSplitTags(good);
ok(st.tags.v==='DMARC1' && st.tags.p==='quarantine','split tags');
ok(st.order[0]==='v','split order');
ok(P.dmSplitTags('P=None').tags.p==='None','tag key lowercased');
ok(P.dmSplitTags('novalue;').order.length===0,'skips tag without equals');
ok(P.dmSplitTags('p=a;p=b').tags.p==='a','first duplicate wins');
ok(P.dmParse('').error!==null,'empty error');
ok(P.dmParse('p=none').error!==null,'missing v error');
ok(P.dmParse('v=SPF1; p=none').error!==null,'wrong v error');
ok(P.dmParse('p=none; v=DMARC1').error!==null,'v must be first');
const pr=P.dmParse('"'+good+'"');
ok(pr.error===null,'quoted record parsed');
ok(pr.tags.sp==='reject','sp tag');
ok(pr.order.length===6,'tag count');
ok(P.dmPolicyScore({p:'reject',sp:'reject',pct:'100',rua:'x',ruf:'y'})===100,'max score');
ok(P.dmPolicyScore({p:'none'})<40,'none low score');
ok(P.dmPolicyScore({p:'reject'})>P.dmPolicyScore({p:'quarantine'}),'reject beats quarantine');
ok(P.dmPolicyScore({p:'reject',pct:'50'})<P.dmPolicyScore({p:'reject',pct:'100'}),'pct affects score');
ok(P.dmPolicyScore({p:'reject',pct:'abc'})===P.dmPolicyScore({p:'reject'}),'invalid pct treated as 100');
ok(P.dmPolicyScore({})>=0,'empty score non negative');
ok(P.dmGrade(95)==='A' && P.dmGrade(80)==='B','grade A B');
ok(P.dmGrade(65)==='C' && P.dmGrade(45)==='D' && P.dmGrade(10)==='F','grade C D F');
ok(P.dmMailtos('mailto:a@b.com, mailto:c@d.com').length===2,'mailtos split');
ok(P.dmMailtos('').length===0,'mailtos empty');
ok(P.dmMailtos(undefined).length===0,'mailtos undefined');
const lint=P.dmLint(pr);
ok(lint.filter(x=>x.level==='\u9519\u8bef').length===0,'good record no errors');
ok(P.dmLint(P.dmParse('v=DMARC1; rua=mailto:a@b.com')).some(x=>x.msg.indexOf('p \u6807\u7b7e')>=0),'missing p error');
ok(P.dmLint(P.dmParse('v=DMARC1; p=bogus')).some(x=>x.level==='\u9519\u8bef'),'bad p value error');
ok(P.dmLint(P.dmParse('v=DMARC1; p=none')).some(x=>x.msg.indexOf('p=none')>=0),'p none advisory');
ok(P.dmLint(P.dmParse('v=DMARC1; p=reject; pct=150')).some(x=>x.msg.indexOf('pct')>=0),'pct out of range');
ok(P.dmLint(P.dmParse('v=DMARC1; p=reject; rua=d@e.com')).some(x=>x.msg.indexOf('mailto:')>=0),'rua missing mailto');
ok(P.dmLint(P.dmParse('v=DMARC1; p=reject; adkim=x')).some(x=>x.msg.indexOf('adkim')>=0),'bad adkim');
ok(P.dmLint(P.dmParse('v=DMARC1; p=reject; fo=9')).some(x=>x.msg.indexOf('fo')>=0),'bad fo');
ok(P.dmLint(P.dmParse('v=DMARC1; p=reject; ri=0')).some(x=>x.msg.indexOf('ri')>=0),'bad ri');
ok(P.dmLint(P.dmParse('v=DMARC1; p=reject; zz=1')).some(x=>x.msg.indexOf('zz')>=0),'unknown tag warned');
ok(P.dmLint(null).length===0,'lint null guard');
const ex=P.dmExplain(pr);
ok(ex.length===8,'explain rows');
ok(ex[0][1].indexOf('\u5783\u573e\u7bb1')>=0,'explain quarantine');
ok(P.dmExplain(P.dmParse('v=DMARC1; p=reject'))[1][1].indexOf('\u7ee7\u627f')>=0,'explain sp inherits');
ok(P.dmExplain(P.dmParse('v=DMARC1; p=none'))[3][1].indexOf('\u5bbd\u677e')>=0,'explain default adkim relaxed');
const b=P.dmBuild({p:'reject',rua:'a@b.com'});
ok(b.indexOf('v=DMARC1')===0,'build starts with v');
ok(b.indexOf('rua=mailto:a@b.com')>=0,'build rua mailto');
ok(P.dmParse(b).error===null,'built record parses');
ok(P.dmBuild({}).indexOf('p=none')>=0,'build default policy');
ok(P.dmBuild({p:'reject',pct:'100'}).indexOf('pct')<0,'build omits pct 100');
ok(P.dmBuild({p:'reject',pct:'50'}).indexOf('pct=50')>=0,'build keeps custom pct');
console.log('PASS '+n+' assertions');
