
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
const TXT='User-agent: *\nDisallow: /admin/\nDisallow: /*.json$\nAllow: /admin/public/\n\nUser-agent: Googlebot\nAllow: /\n\nSitemap: https://example.com/sitemap.xml';
const p=P.rbParse(TXT);
ok(p.groups.length===2,'two groups');
ok(p.groups[0].agents[0]==='*' && p.groups[1].agents[0]==='googlebot','agents lowercased');
ok(p.groups[0].rules.length===3,'group rules');
ok(p.sitemaps.length===1 && p.sitemaps[0].indexOf('sitemap.xml')>0,'sitemap');
ok(p.errors.length===0,'no errors');
ok(P.rbParse('# only comment\n').groups.length===0,'comments stripped');
ok(P.rbParse('garbage').errors.length===1,'missing colon error');
ok(P.rbParse('Disallow: /x').errors.length===1,'rule before UA');
ok(P.rbParse('User-agent: *\nCrawl-delay: 2').groups[0].crawlDelay===2,'crawl delay');
ok(P.rbParse(null).groups.length===0,'null safe');
ok(P.rbMatchPattern('/admin/','/admin/x')===true,'prefix match');
ok(P.rbMatchPattern('/admin/','/user/')===false,'no match');
ok(P.rbMatchPattern('/*.json$','/a/b.json')===true,'wildcard + anchor');
ok(P.rbMatchPattern('/*.json$','/a/b.jsonx')===false,'anchor enforced');
ok(P.rbMatchPattern('','/x')===false,'empty pattern never matches');
ok(P.rbMatchPattern('/','/anything')===true,'root matches all');
ok(P.rbPickGroup(p,'Googlebot').agents[0]==='googlebot','pick specific ua');
ok(P.rbPickGroup(p,'SomeBot').agents[0]==='*','fallback star');
ok(P.rbPickGroup({groups:[]},'x')===null,'no groups');
ok(P.rbAllowed(p,'Bingbot','/admin/panel').allowed===false,'disallow admin');
ok(P.rbAllowed(p,'Bingbot','/admin/public/a').allowed===true,'longest allow wins');
ok(P.rbAllowed(p,'Bingbot','/data/x.json').allowed===false,'json disallowed');
ok(P.rbAllowed(p,'Googlebot','/admin/panel').allowed===true,'googlebot group allows');
ok(P.rbAllowed(p,'Bingbot','/public').allowed===true,'unmatched allowed');
ok(P.rbAllowed({groups:[]},'x','/y').allowed===true,'empty parsed allows');
const built=P.rbBuild({ groups:[{ agents:['*'], disallow:['/x/'], allow:[], crawlDelay:1 }], sitemaps:['https://e.com/s.xml'] });
ok(built.indexOf('User-agent: *')===0,'build head');
ok(built.indexOf('Crawl-delay: 1')>0 && built.indexOf('Sitemap: https://e.com/s.xml')>0,'build fields');
ok(P.rbParse(built).groups.length===1,'build roundtrip');
ok(P.rbBuild().indexOf('User-agent: *')===0,'build default');
console.log('PASS '+n+' assertions');
