const { JSDOM } = require('C:/Users/53014/.workbuddy/binaries/node/workspace/node_modules/jsdom');
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true});
const {window}=dom; const errs=[]; window.addEventListener('error',e=>errs.push(e.message));
setTimeout(()=>{ const doc=window.document; let pass=0,fail=0;
  const ok=(n,c)=>c?pass++:(fail++,console.error('  FAIL: '+n));
  ok('LuhnForgePure exposed', typeof window.LuhnForgePure==='object');
  ok('run btn', !!doc.getElementById('run'));
  ok('default valid', (doc.getElementById('out').textContent||'').indexOf('合法')>=0);
  doc.getElementById('in').value='4111111111111112'; doc.getElementById('run').click();
  ok('invalid detect', (doc.getElementById('out').textContent||'').indexOf('非法')>=0);
  ok('brand shown', (doc.getElementById('out').textContent||'').indexOf('Visa')>=0);
  ok('no js errors', errs.length===0);
  if(errs.length) console.error('  js errors:',errs);
  console.log('LuhnForge smoke: '+pass+' passed, '+fail+' failed');
  process.exit(fail?1:0);
},400);
