
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
ok(P.BASE83.length===83, 'base83 alphabet length');
ok(P.decode83('0')===0, 'decode83 zero');
ok(P.decode83('1')===1, 'decode83 one');
ok(P.decode83('A')===10, 'decode83 letter A');
ok(P.decode83('L')===21, 'decode83 letter L');
ok(P.decode83('10')===83, 'decode83 two digits');
ok(P.decode83('!')===-1, 'decode83 rejects invalid char');
ok(P.encode83(0,1)==='0', 'encode83 zero');
ok(P.encode83(83,2)==='10', 'encode83 carry');
ok(P.encode83(21,1)==='L', 'encode83 letter');
for(var v=0;v<200;v+=7){ if(P.decode83(P.encode83(v,3))!==v){ console.error('FAIL: base83 roundtrip '+v); process.exit(1);} }
n++;
ok(Math.abs(P.srgbToLinear(0))<1e-9, 'srgbToLinear black');
ok(Math.abs(P.srgbToLinear(255)-1)<1e-9, 'srgbToLinear white');
ok(P.linearToSrgb(0)===0, 'linearToSrgb black');
ok(P.linearToSrgb(1)===255, 'linearToSrgb white');
ok(P.linearToSrgb(2)===255, 'linearToSrgb clamps high');
ok(P.linearToSrgb(-1)===0, 'linearToSrgb clamps low');
for(var c=0;c<=255;c+=17){ if(P.linearToSrgb(P.srgbToLinear(c))!==c){ console.error('FAIL: srgb roundtrip '+c); process.exit(1);} }
n++;
ok(P.signPow(-4,0.5)===-2, 'signPow negative');
ok(P.signPow(4,0.5)===2, 'signPow positive');
var p=P.parseHash('LEHV6nWB2yk8pyo0adR*.7kCMdnj');
ok(p.valid===true, 'reference blurhash valid');
ok(p.componentX===4 && p.componentY===3, 'reference blurhash 4x3 components');
ok(p.length===28, 'reference blurhash length 28');
ok(P.parseHash('abc').valid===false, 'too short rejected');
ok(P.parseHash('LEHV6nWB2yk8pyo0adR*.7kCMdn').valid===false, 'wrong length rejected');
ok(P.parseHash('LEHV6nWB2yk8pyo0adR*.7kCMdn\u4e2d').error.indexOf('base83')>-1, 'non base83 rejected');
var avg=P.averageColor('LEHV6nWB2yk8pyo0adR*.7kCMdnj');
ok(/^#[0-9a-f]{6}$/.test(avg.hex), 'averageColor hex format');
ok(avg.r>=0 && avg.r<=255, 'averageColor channel range');
ok(P.averageColor('bad').hex===null, 'averageColor invalid hash');
var d=P.decodeBlurhash('LEHV6nWB2yk8pyo0adR*.7kCMdnj', 8, 8, 1);
ok(d.error===null, 'decode reference hash');
ok(d.pixels.length===8*8*4, 'decoded pixel buffer size');
ok(d.pixels[3]===255, 'decoded alpha opaque');
ok(d.pixels.every(function(x){ return x>=0 && x<=255; }), 'decoded channels in range');
ok(P.decodeBlurhash('bad',4,4).error!==null, 'decode invalid hash errors');
ok(P.solidPixels(4,4,1,2,3).length===64, 'solidPixels buffer size');
ok(P.solidPixels(2,2,1,2,3)[3]===255, 'solidPixels alpha opaque');
var sp=P.solidPixels(32,32,30,60,90);
var e=P.encodeBlurhash(sp, 32, 32, 4, 3);
ok(e.error===null, 'encode solid image');
ok(P.parseHash(e.hash).valid===true, 'encoded hash is valid');
ok(P.parseHash(e.hash).componentX===4 && P.parseHash(e.hash).componentY===3, 'encoded components preserved');
var ea=P.averageColor(e.hash);
ok(ea.r===30 && ea.g===60 && ea.b===90, 'solid colour survives roundtrip exactly');
var back=P.decodeBlurhash(e.hash, 8, 8, 1);
var ci=4*4 + 4*(8*4);
ok(back.pixels[ci]===30, 'decoded solid red channel at centre');
ok(back.pixels[ci+1]===60, 'decoded solid green channel at centre');
ok(back.pixels[ci+2]===90, 'decoded solid blue channel at centre');
var lo=999, hi=-1;
for(var q=0;q<64;q++){ var vv=back.pixels[q*4]; if(vv<lo) lo=vv; if(vv>hi) hi=vv; }
ok(hi-lo<=8, 'solid image decodes to near uniform field');
var W=16,H=16,grad=new Array(W*H*4);
for(var y=0;y<H;y++){ for(var x=0;x<W;x++){ var t=x/(W-1), i=4*x+y*W*4;
  grad[i]=Math.round(20+200*t); grad[i+1]=40; grad[i+2]=Math.round(220-200*t); grad[i+3]=255; } }
var ge=P.encodeBlurhash(grad, W, H, 4, 3);
ok(ge.error===null, 'encode gradient');
var gd=P.decodeBlurhash(ge.hash, W, H, 1);
ok(gd.pixels[0] < gd.pixels[4*(W-1)], 'gradient red increases left to right');
ok(gd.pixels[2] > gd.pixels[4*(W-1)+2], 'gradient blue decreases left to right');
ok(P.encodeBlurhash([1,2,3], 4, 4).error!==null, 'encode rejects wrong buffer size');
ok(P.encodeBlurhash(P.solidPixels(2,2,0,0,0),2,2,1,1).hash.length===6, 'single component hash length 6');
ok(P.encodeBlurhash(P.solidPixels(2,2,0,0,0),2,2,20,20).componentX===9, 'component count clamped to 9');
var g2=P.toCssGradient('LEHV6nWB2yk8pyo0adR*.7kCMdnj', 3);
ok(g2.layers===9, 'css gradient 3x3 layers');
ok(g2.css.indexOf('background-color: #')>-1, 'css includes average colour');
ok(g2.css.indexOf('radial-gradient')>-1, 'css includes radial gradients');
ok(P.toCssGradient('bad').css===null, 'css gradient invalid hash');
var cost=P.hashCost('LEHV6nWB2yk8pyo0adR*.7kCMdnj');
ok(cost.bytes===28, 'hashCost byte count');
ok(cost.components===12, 'hashCost component count');
ok(cost.note.indexOf('28 字节')>-1, 'hashCost note text');
console.log('BlurhashForge _test: '+n+' passed, 0 failed');
