
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
var p=P.parsePolicy("default-src 'self'; script-src 'self' https://cdn.x");
ok(p.order.length===2, 'parsePolicy two directives');
ok(p.directives['script-src'].length===2, 'parsePolicy source count');
ok(P.parsePolicy("Content-Security-Policy: default-src 'self'").directives['default-src'][0]==="'self'", 'header prefix stripped');
ok(P.parsePolicy("default-src 'self'; default-src 'none'").errors.length===1, 'duplicate directive flagged');
ok(P.parsePolicy('upgrade-insecure-requests').directives['upgrade-insecure-requests'].length===0, 'valueless directive parsed');
ok(P.serialize({'default-src':["'self'"]},['default-src'])==="default-src 'self'", 'serialize simple');
ok(P.serialize({'upgrade-insecure-requests':[]},['upgrade-insecure-requests'])==='upgrade-insecure-requests', 'serialize valueless');
ok(P.isSourceValid("'self'")===true, "keyword 'self' valid");
ok(P.isSourceValid("'nonce-abc12345XYZ'")===true, 'nonce source valid');
ok(P.isSourceValid("'sha256-abc+/='")===true, 'hash source valid');
ok(P.isSourceValid('https:')===true, 'scheme source valid');
ok(P.isSourceValid('*.example.com')===true, 'wildcard host valid');
ok(P.isSourceValid('')===false, 'empty source invalid');
ok(P.isSourceValid("'bogus'")===false, 'unknown quoted keyword invalid');
var a1=P.auditPolicy("default-src 'self'; script-src 'self' 'unsafe-inline'");
ok(a1.errors>=1, 'unsafe-inline script is error');
var a2=P.auditPolicy("script-src 'nonce-abc12345' 'unsafe-inline'");
ok(a2.issues.some(function(i){return i.level==='info' && i.msg.indexOf('降级')>-1;}), 'nonce plus unsafe-inline is info not error');
ok(P.auditPolicy("script-src 'self' 'unsafe-eval'").warnings>=1, 'unsafe-eval warns');
ok(P.auditPolicy("script-src *").errors>=1, 'script wildcard error');
ok(P.auditPolicy("script-src 'self' data:").errors>=1, 'script data uri error');
ok(P.auditPolicy("script-src 'self' http:").warnings>=1, 'script http warns');
ok(P.auditPolicy("img-src 'self'").errors>=1, 'missing default-src and script-src is error');
ok(P.auditPolicy("script-src 'strict-dynamic'").errors>=1, 'strict-dynamic without nonce error');
ok(P.auditPolicy("script-src 'strict-dynamic' 'nonce-abcd1234'").issues.every(function(i){return i.msg.indexOf('strict-dynamic')===-1;}), 'strict-dynamic with nonce ok');
ok(P.auditPolicy("default-src 'self'; script-src 'self' bad source'").errors>=1, 'invalid source expression error');
var clean=P.buildPolicy({mode:'lockdown'});
var ac=P.auditPolicy(clean.value);
ok(ac.errors===0, 'lockdown policy has no errors');
ok(ac.grade==='A' || ac.grade==='B', 'lockdown policy grades well');
ok(P.auditPolicy("script-src 'self' *").grade==='D' || P.auditPolicy("script-src 'self' *").grade==='F' || P.auditPolicy("script-src 'self' *").grade==='C', 'wildcard policy grades poorly');
var b=P.buildPolicy({mode:'strict', nonce:'abcd1234efgh'});
ok(b.value.indexOf("'nonce-abcd1234efgh'")>-1, 'buildPolicy injects nonce');
ok(b.value.indexOf("'strict-dynamic'")>-1, 'buildPolicy strict-dynamic');
ok(b.value.indexOf("object-src 'none'")>-1, 'buildPolicy object-src none');
ok(b.header.indexOf('Content-Security-Policy:')===0, 'buildPolicy header name');
ok(P.buildPolicy({reportOnly:true}).header.indexOf('Report-Only')>-1, 'report-only header name');
ok(P.buildPolicy({mode:'basic'}).directives['img-src'].length===3, 'basic img-src sources');
ok(P.buildPolicy({mode:'lockdown'}).directives['default-src'][0]==="'none'", 'lockdown default-src none');
ok(P.buildPolicy({mode:'basic', upgradeInsecure:true}).value.indexOf('upgrade-insecure-requests')>-1, 'upgrade flag appended');
ok(P.buildPolicy({mode:'basic', reportUri:'/r'}).value.indexOf('report-uri /r')>-1, 'report-uri appended');
var ex=P.buildPolicy({mode:'basic', extra:{'connect-src':["'self'",'https://api.x'],'img-src':['blob:']}});
ok(ex.directives['connect-src'].length===2, 'extra new directive added');
ok(ex.directives['img-src'].indexOf('blob:')>-1, 'extra merged into existing directive');
ok(ex.directives['img-src'].length===4, 'extra merge does not duplicate');
ok(P.makeNonce('a')===P.makeNonce('a'), 'makeNonce deterministic');
ok(P.makeNonce('a')!==P.makeNonce('b'), 'makeNonce varies by seed');
ok(P.makeNonce('a').length===22, 'makeNonce length');
var d=P.diffPolicy("default-src 'self'; script-src 'self'", "default-src 'self'; script-src 'none'; img-src *");
ok(d.added.length===1 && d.added[0]==='img-src', 'diff detects added');
ok(d.changed.length===1 && d.changed[0].name==='script-src', 'diff detects changed');
ok(P.diffPolicy("default-src 'self'","default-src 'self'").same===true, 'diff same policies');
ok(P.diffPolicy("a 'self'; b 'self'","a 'self'").removed.length===1, 'diff detects removed');
console.log('CspForge _test: '+n+' passed, 0 failed');
