const { JSDOM } = require('C:/Users/53014/.workbuddy/binaries/node/workspace/node_modules/jsdom');
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true});
const {window}=dom; const errs=[]; window.addEventListener('error',e=>errs.push(e.message));
setTimeout(()=>{ const doc=window.document; let pass=0,fail=0;
  const ok=(n,c)=>c?pass++:(fail++,console.error('  FAIL: '+n));
  ok('HexForgePure exposed', typeof window.HexForgePure==='object');
  ok('run btn', !!doc.getElementById('run'));
  doc.getElementById('in').value='4142'; doc.getElementById('mode').value='hex'; doc.getElementById('run').click();
  var out=doc.getElementById('out').textContent||'';
  ok('output has hex', out.indexOf('41 42')>0);
  ok('stat shown', (doc.getElementById('stat').textContent||'').indexOf('字节')>=0);
  doc.getElementById('mode').value='text'; doc.getElementById('in').value='Hi'; doc.getElementById('run').click();
  ok('text mode dump', (doc.getElementById('out').textContent||'').indexOf('48 69')>0);
  ok('no js errors', errs.length===0);
  if(errs.length) console.error('  js errors:',errs);
  console.log('HexForge smoke: '+pass+' passed, '+fail+' failed');
  process.exit(fail?1:0);
},400);
