
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
ok(P.LC_MODELS.length===10,'ten models');
ok(P.LC_MODELS.every(m=>m.inp>=0 && m.out>=0 && m.ctx>0),'model fields sane');
ok(P.LC_MODELS.every(m=>m.out>=m.inp),'output price not cheaper than input');
ok(P.lcFindModel('gpt-4o').label==='GPT-4o','find model');
ok(P.lcFindModel('nope')===null,'find model null');
ok(P.lcEstimateTokens('')===0,'estimate empty');
ok(P.lcEstimateTokens('hello world')>0,'estimate ascii');
ok(P.lcEstimateTokens('\u4e2d\u6587\u6d4b\u8bd5\u6587\u672c')>=4,'estimate cjk denser');
ok(P.lcEstimateTokens('\u4e2d\u6587')>P.lcEstimateTokens('ab'),'cjk more tokens than same length ascii');
ok(P.lcEstimateTokens('x')===1,'estimate min one');
const gm=P.lcFindModel('gpt-4o');
const c=P.lcCost(gm, 1e6, 1e6);
ok(Math.abs(c.input-2.5)<1e-9,'input cost per million');
ok(Math.abs(c.output-10)<1e-9,'output cost per million');
ok(Math.abs(c.total-12.5)<1e-9,'total cost');
ok(P.lcCost(gm,0,0).total===0,'zero tokens zero cost');
ok(P.lcCost(null,1,1)===null,'cost null model');
ok(P.lcCost(P.lcFindModel('local-0'),1e6,1e6).total===0,'local model free');
ok(P.lcRound(1.23456789,2)===1.23,'round two digits');
ok(P.lcRound(1.23456789)===1.234568,'round default six');
ok(P.lcFmtUsd(0)==='$0','fmt zero');
ok(P.lcFmtUsd(0.000123)==='$0.000123','fmt micro');
ok(P.lcFmtUsd(0.5)==='$0.5000','fmt sub dollar');
ok(P.lcFmtUsd(12.345)==='$12.35','fmt dollars');
const pr=P.lcProject(gm, 1000, 1000, 100, 7.2);
ok(Math.abs(pr.per-0.0125)<1e-9,'project per call');
ok(Math.abs(pr.day-1.25)<1e-9,'project daily');
ok(Math.abs(pr.month-37.5)<1e-9,'project monthly');
ok(Math.abs(pr.year-pr.day*365)<1e-9,'project yearly');
ok(Math.abs(pr.monthCny-37.5*7.2)<1e-6,'project cny');
ok(P.lcProject(gm,1,1,0).day===0,'zero calls zero daily');
ok(P.lcProject(null,1,1,1)===null,'project null model');
const cmp=P.lcCompare(1000,1000,10);
ok(cmp.length===10,'compare all models');
ok(cmp[0].per<=cmp[cmp.length-1].per,'compare sorted ascending');
ok(cmp[0].id==='local-0','free model cheapest');
ok(cmp.every(x=>x.fits===true),'small request fits all');
ok(P.lcCompare(500000,0,1).some(x=>x.fits===false),'huge request exceeds some windows');
const cs=P.lcCacheSaving(gm, 1e6, 0, 1, 0.9);
ok(Math.abs(cs.saved-2.25)<1e-9,'cache saving full hit');
ok(Math.abs(cs.cached-0.25)<1e-9,'cached cost');
ok(Math.abs(cs.pct-0.9)<1e-9,'cache pct');
ok(P.lcCacheSaving(gm,1e6,0,0).saved===0,'no hit no saving');
ok(P.lcCacheSaving(gm,1e6,0,5).saved===P.lcCacheSaving(gm,1e6,0,1).saved,'hit rate clamped');
ok(P.lcCacheSaving(gm,0,0,1).pct===0,'zero cost pct guard');
ok(P.lcCacheSaving(null,1,1,1)===null,'cache null model');
ok(P.lcCtxWarn(gm, 1000, 100).level==='\u6b63\u5e38','ctx normal');
ok(P.lcCtxWarn(gm, 120000, 0).level==='\u8b66\u544a','ctx warning');
ok(P.lcCtxWarn(gm, 200000, 0).level==='\u9519\u8bef','ctx error');
ok(P.lcCtxWarn(null,1,1)===null,'ctx null model');
console.log('PASS '+n+' assertions');
