
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
ok(P.cfB64Encode('hi')==='aGk=','b64 encode');
ok(P.cfB64Decode('aGk=')==='hi','b64 decode');
ok(P.cfB64Decode(P.cfB64Encode('nano-tools'))==='nano-tools','b64 roundtrip');
ok(P.cfB64Decode(P.cfB64Encode('\u4e2d\u6587\u6d4b\u8bd5'))==='\u4e2d\u6587\u6d4b\u8bd5','b64 utf8 roundtrip');
ok(P.cfB64Decode('!!!')===null,'b64 reject invalid');
ok(P.cfHexEncode('AB')==='41 42','hex encode');
ok(P.cfHexDecode('41 42')==='AB','hex decode');
ok(P.cfHexDecode('0x41,0x42')==='AB','hex decode with prefix');
ok(P.cfHexDecode('4')===null,'hex odd length null');
ok(P.cfHexDecode('zz')===null,'hex invalid null');
ok(P.cfRot('abc',13)==='nop','rot13');
ok(P.cfRot(P.cfRot('Hello',13),13)==='Hello','rot13 involution');
ok(P.cfRot('a',-1)==='z','rot negative wraps');
ok(P.cfRot('123!',13)==='123!','rot leaves non alpha');
ok(P.cfUrlEncode('a b')==='a%20b','url encode');
ok(P.cfUrlDecode('a%20b')==='a b','url decode');
ok(P.cfUrlDecode('%E0%A4%A')===null,'url decode invalid null');
ok(P.cfReverse('abc')==='cba','reverse');
ok(P.cfXor(P.cfXor('secret','k'),'k')==='secret','xor involution');
ok(P.cfXor('abc','')==='abc','xor empty key passthrough');
ok(P.cfEntropy('aaaa')===0,'entropy zero');
ok(P.cfEntropy('ab')===1,'entropy one bit');
ok(P.cfEntropy('')===0,'entropy empty');
const rec=P.cfParseRecipe('# comment\nb64e\nrot13\n');
ok(rec.length===2 && rec[0].op==='b64e','parse recipe skips comments');
ok(P.cfParseRecipe('xor mykey')[0].arg==='mykey','parse recipe arg');
ok(P.cfParseRecipe('')  .length===0,'parse empty recipe');
const r1=P.cfRun('hi',[{op:'b64e'}]);
ok(r1.error===null && r1.output==='aGk=','run single op');
const r2=P.cfRun('hi',[{op:'b64e'},{op:'b64d'}]);
ok(r2.output==='hi' && r2.steps.length===2,'run chain roundtrip');
const r3=P.cfRun('hi',[{op:'nope'}]);
ok(r3.error!==null && r3.failAt===0,'run unknown op');
const r4=P.cfRun('!!!',[{op:'b64d'}]);
ok(r4.error!==null && r4.output===null,'run op failure reported');
const r5=P.cfRun('keep',[]);
ok(r5.error===null && r5.output==='keep','run empty recipe passthrough');
ok(P.cfRun(null,[]).output==='','run null input');
ok(P.cfRun('a',[{op:'xor',arg:'k'},{op:'xor',arg:'k'}]).output==='a','run xor chain');
ok(P.cfRun('Ab',[{op:'upper'}]).output==='AB','run upper');
ok(P.cfRun(' x ',[{op:'trim'}]).output==='x','run trim');
ok(P.cfRun('a b',[{op:'strip'}]).output==='ab','run strip');
ok(P.cfRun('hi',[{op:'b64e'},{op:'rot13'}]).steps[1].len===4,'step length recorded');
console.log('PASS '+n+' assertions');
