
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const kernel=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1])[0];
const mo={exports:{}};new Function('module','exports',kernel)(mo,mo.exports);
const C=mo.exports;let pass=0,fail=0;
function ok(n,c){if(c)pass++;else{fail++;console.error('FAIL '+n);}}
ok('b64-hi', C.b64e(C.utf8('hi'))==='aGk=');
ok('b64-man', C.b64e(C.utf8('Man'))==='TWFu');
ok('b64-rt', C.fromUtf8(C.b64d('aGVsbG8='))==='hello');
ok('b64-bad', C.b64d('!!!')===null);
ok('utf8-cn', C.b64e(C.utf8('\u4f60\u597d'))==='5L2g5aW9');
ok('utf8-rt', C.fromUtf8(C.utf8('\u4f60\u597d abc'))==='\u4f60\u597d abc');
ok('utf8-emoji', C.fromUtf8(C.utf8('\ud83d\ude00'))==='\ud83d\ude00');
ok('mime-png', C.guessMime('a/b/c.PNG')==='image/png');
ok('mime-unknown', C.guessMime('noext')==='application/octet-stream');
ok('mime-svg', C.guessMime('i.svg')==='image/svg+xml');
var e=C.encodeText('Hello nano-tools','text/plain');
ok('enc-uri', e.value.uri==='data:text/plain;base64,SGVsbG8gbmFuby10b29scw==');
ok('enc-raw', e.value.raw===16);
ok('enc-mode', e.value.mode==='base64');
ok('enc-css', e.value.css.indexOf('url("data:')===0);
var p=C.parse(e.value.uri);
ok('parse-mime', p.value.mime==='text/plain');
ok('parse-b64', p.value.base64===true);
ok('parse-text', p.value.text==='Hello nano-tools');
ok('parse-size', p.value.size===16);
var pe=C.encodeText('<svg a="b"/>','image/svg+xml',{mode:'pct'});
ok('pct-mode', pe.value.mode==='pct');
ok('pct-nob64', pe.value.uri.indexOf(';base64')<0);
ok('pct-escape', pe.value.uri.indexOf('%3Csvg')>=0);
var pp=C.parse(pe.value.uri);
ok('pct-rt', pp.value.text==='<svg a="b"/>');
var cs=C.parse('data:text/plain;charset=utf-8;base64,aGk=');
ok('charset', cs.value.params.charset==='utf-8');
ok('charset-text', cs.value.text==='hi');
ok('bad-scheme', C.parse('http://x').error!=null);
ok('bad-comma', C.parse('data:text/plain').error!=null);
ok('bad-b64', C.parse('data:text/plain;base64,@@@').error!=null);
ok('enc-bad', C.encode(null,'text/plain').error!=null);
ok('size-fmt', C.fmtSize(2048)==='2.0 KB');
ok('size-b', C.fmtSize(12)==='12 B');
console.log((fail?'FAIL':'PASS')+' DataUriForge '+pass+'/'+fail);process.exit(fail?1:0);
