
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
ok(P.PROTOCOLS.length===5, 'five protocol entries');
ok(P.protocolInfo('TLS1.3').grade==='A', 'TLS1.3 grade A');
ok(P.protocolInfo('tls1.0').grade==='D', 'TLS1.0 grade D case insensitive');
ok(P.protocolInfo('TLSv1.2').grade==='B', 'TLSv prefix normalised');
ok(P.protocolInfo('QUIC')===null, 'unknown protocol null');
var c13=P.parseCipher('TLS_AES_256_GCM_SHA384');
ok(c13.tls13===true, 'TLS1.3 suite detected');
ok(c13.pfs===true && c13.aead===true, 'TLS1.3 suite pfs and aead');
ok(c13.enc==='AES-256-GCM', 'TLS1.3 aes256 gcm');
ok(P.parseCipher('TLS_CHACHA20_POLY1305_SHA256').enc==='CHACHA20-POLY1305', 'TLS1.3 chacha');
var ce=P.parseCipher('ECDHE-RSA-AES128-GCM-SHA256');
ok(ce.kx==='ECDHE' && ce.auth==='RSA', 'ecdhe rsa kx and auth');
ok(ce.aead===true && ce.pfs===true, 'gcm suite aead pfs');
var cr=P.parseCipher('AES128-SHA');
ok(cr.pfs===false, 'static rsa no pfs');
ok(cr.mac==='SHA1', 'sha1 mac detected');
ok(P.parseCipher('DES-CBC3-SHA').enc==='3DES', '3des detected');
ok(P.parseCipher('RC4-MD5').enc==='RC4', 'rc4 detected');
ok(P.parseCipher('RC4-MD5').mac==='MD5', 'md5 mac detected');
ok(P.parseCipher('').valid===false, 'empty cipher invalid');
ok(P.gradeCipher('TLS_AES_128_GCM_SHA256').grade==='A', 'tls13 suite grade A');
ok(P.gradeCipher('TLS_AES_128_GCM_SHA256').issues.length===0, 'tls13 suite no issues');
ok(P.gradeCipher('RC4-MD5').score < 35, 'rc4 md5 very low score');
ok(P.gradeCipher('NULL-SHA').score===0, 'null cipher zero score');
ok(P.gradeCipher('DES-CBC3-SHA').issues.length>=1, '3des flagged');
ok(P.gradeCipher('AES128-SHA').issues.some(function(x){return x.indexOf('前向保密')>-1;}), 'no pfs flagged');
var a=P.auditSuite(['TLS_AES_128_GCM_SHA256','ECDHE-RSA-AES128-GCM-SHA256']);
ok(a.total===2 && a.grade==='A', 'clean suite list grade A');
ok(a.pfsRatio===100 && a.aeadRatio===100, 'clean suite ratios');
var b=P.auditSuite('TLS_AES_128_GCM_SHA256:RC4-MD5');
ok(b.total===2, 'colon separated parsed');
ok(b.grade==='F' || b.grade==='E', 'worst cipher drags grade down');
ok(P.auditSuite('').total===0, 'empty audit total zero');
var h=P.buildHsts({maxAge:31536000, includeSubDomains:true, preload:true});
ok(h.value==='max-age=31536000; includeSubDomains; preload', 'hsts full header');
ok(h.preloadReady===true, 'hsts preload ready');
ok(h.warnings.length===0, 'hsts valid no warnings');
ok(P.buildHsts({maxAge:31536000, preload:true}).warnings.length===1, 'preload without subdomains warns');
ok(P.buildHsts({maxAge:600, includeSubDomains:true, preload:true}).warnings.length===2, 'short maxage preload two warnings');
ok(P.buildHsts({}).value==='max-age=31536000', 'hsts default max-age');
ok(P.certDays(-3).level==='expired', 'cert expired');
ok(P.certDays(5).level==='critical', 'cert critical');
ok(P.certDays(21).level==='warn', 'cert warn');
ok(P.certDays(200).level==='ok', 'cert ok');
ok(P.certDays('x').level==='unknown', 'cert unknown');
ok(P.recommendConfig('modern').protocols.length===1, 'modern config only tls13');
ok(P.recommendConfig('intermediate').ciphers.length>=5, 'intermediate cipher list');
ok(P.recommendConfig('nope')===null, 'unknown config null');
console.log('TlsForge _test: '+n+' passed, 0 failed');
