
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
var r1=P.rxExplain('a');
ok(r1.valid && r1.parts.length===1,'single literal');
ok(r1.parts[0].desc.indexOf('字面')>=0,'literal desc');
var r2=P.rxExplain('^a$');
ok(r2.parts.length===3,'anchors 3 parts');
var r3=P.rxExplain('\\d+');
ok(r3.valid && r3.parts[0].desc.indexOf('数字')>=0,'digit class');
var r4=P.rxExplain('[a-z]');
ok(r4.valid && r4.parts[0].desc.indexOf('字符集')>=0,'char class');
var r5=P.rxExplain('[^0-9]');
ok(r5.parts[0].desc.indexOf('排除')>=0,'negated class');
var r6=P.rxExplain('(abc)');
ok(r6.parts.some(function(p){return p.desc.indexOf('捕获分组')>=0;}),'capturing group');
var r7=P.rxExplain('(?:a)');
ok(r7.parts.some(function(p){return p.desc.indexOf('非捕获')>=0;}),'non-capturing group');
var r8=P.rxExplain('a{2,4}');
ok(r8.parts[1].desc==='2-4 次','range quantifier');
var r9=P.rxExplain('a{3}');
ok(r9.parts[1].desc==='精确 3 次','exact quantifier');
var r10=P.rxExplain('a|b');
ok(r10.parts.some(function(p){return p.desc.indexOf('或')>=0;}),'alternation');
var r11=P.rxExplain('\\w\\s\\b');
ok(r11.parts.length===3 && r11.parts[1].desc.indexOf('空白')>=0,'escapes');
var r12=P.rxExplain('(abc');
ok(!r12.valid && /未闭合/.test(r12.error),'unclosed group error');
var r13=P.rxExplain('a[');
ok(!r13.valid && /]/.test(r13.error),'unclosed class error');
var r14=P.rxExplain('a\\');
ok(!r14.valid,'dangling backslash');
var r15=P.rxExplain('a*?');
ok(r15.valid && r15.parts.length===3,'lazy quant ok');
var r16=P.rxExplain('^ab$c','gi');
ok(r16.valid && r16.summary.indexOf('忽略大小写')>=0 && r16.summary.indexOf('全局')>=0,'flags summary');
ok(P.rxExplain('.+*').valid,'complex valid');
console.log('PASS '+n+' assertions');
