const { JSDOM } = require('C:/Users/53014/.workbuddy/binaries/node/workspace/node_modules/jsdom');
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true});
const {window}=dom; const errs=[]; window.addEventListener('error',e=>errs.push(e.message||String(e.error)));
setTimeout(()=>{ const doc=window.document; let pass=0,fail=0;
  const ok=(n,c)=>c?pass++:(fail++,console.error('  FAIL: '+n));
  ok('SnowflakeForgePure exposed', typeof window.SnowflakeForgePure==='object');
  ok('run btn', !!doc.getElementById('run'));
  doc.getElementById('sid').value='0'; doc.getElementById('run').click();
  var out=doc.getElementById('out').textContent;
  ok('output produced', out.length>0 && out.indexOf('2010')>=0);
  ok('shows epoch', out.indexOf('1288834974657')>=0);
  ok('no js errors', errs.length===0);
  if(errs.length) console.error('  js errors:',errs);
  console.log('SnowflakeForge smoke: '+pass+' passed, '+fail+' failed');
  process.exit(fail?1:0);
},500);
