
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
const q='query GetUser($id: ID!, $first: Int = 10) {\n  user(id: $id) {\n    id\n    posts(first: $first) { edges { node { id } } }\n  }\n}';
ok(P.gqStrip('a # note\nb').replace(/[ \t]+/g,'')==='a\nb','strip comments');
ok(P.gqTokens('{ a }').length===3,'tokens basic');
ok(P.gqTokens('...Frag').indexOf('...')>=0,'tokens spread');
ok(P.gqTokens('"a b"').length===1,'tokens string literal');
ok(P.gqBalance('{ a }').ok===true,'balance ok');
ok(P.gqBalance('{ a').ok===false,'balance unclosed');
ok(P.gqBalance('{ a )').ok===false,'balance mismatch');
ok(P.gqBalance('{ a(b:1) { c } }').ok===true,'balance nested');
ok(P.gqParse('').error!==null,'empty error');
ok(P.gqParse('query Broken {').error!==null,'unbalanced error');
ok(P.gqParse('no braces here').error!==null,'no body error');
const p=P.gqParse(q);
ok(p.error===null,'parse ok');
ok(p.op==='query' && p.name==='GetUser','op and name');
ok(p.vars.length===2,'two variables');
ok(p.vars[0].name==='id' && p.vars[0].required===true,'required variable');
ok(p.vars[1].def==='10','variable default');
ok(p.vars[1].required===false,'optional variable');
ok(p.used.id===1 && p.used.first===1,'usage counted');
ok(P.gqParse('mutation { a }').op==='mutation','mutation op');
ok(P.gqParse('{ a }').op==='query','anonymous defaults to query');
ok(P.gqParse('{ a }').name===null,'anonymous no name');
const fr=P.gqParse('query Q { u { ...F } }\nfragment F on User { id }');
ok(fr.frags.length===1 && fr.frags[0].on==='User','fragment parsed');
ok(fr.spreads.indexOf('F')>=0,'spread parsed');
ok(P.gqParse('{ a @include(if: true) }').directives.indexOf('include')>=0,'directive parsed');
const f=P.gqFields(p.body);
ok(f.maxDepth>=3,'field depth');
ok(f.fields.length>=4,'field count');
ok(P.gqFields('{ a: b }').fields[0].alias==='a','alias captured');
ok(P.gqFields('{ a: b }').fields[0].name==='b','alias target name');
ok(P.gqFields('').fields.length===0,'empty body no fields');
ok(P.gqFields('{ a { b { c } } }').maxDepth===3,'inline nesting depth');
ok(P.gqFields('{ a { b c } }').fields.length===3,'inline siblings counted');
ok(P.gqFields('{ a(x: 1, y: "z") }').fields.length===1,'argument names not counted as fields');
ok(P.gqFields('{ a @skip(if: true) }').fields.length===1,'directive not counted as field');
ok(P.gqFields('{ ...Frag b }').fields.length===1,'fragment spread name not counted');
const lint=P.gqLint(p);
ok(lint.length===0,'clean query no lint');
ok(P.gqLint(P.gqParse('query Q($x: Int) { a }')).some(s=>s.indexOf('\u672a\u88ab\u4f7f\u7528')>=0),'unused variable');
ok(P.gqLint(P.gqParse('query Q { a(id: $zz) }')).some(s=>s.indexOf('\u672a\u58f0\u660e')>=0),'undeclared variable');
ok(P.gqLint(P.gqParse('query Q { ...Missing }')).some(s=>s.indexOf('\u672a\u5b9a\u4e49')>=0),'missing fragment');
ok(P.gqLint(P.gqParse('query Q { a }\nfragment Un on X { y }')).some(s=>s.indexOf('\u672a\u88ab\u4f7f\u7528')>=0),'unused fragment');
ok(P.gqLint(P.gqParse('mutation { a }')).some(s=>s.indexOf('\u547d\u540d')>=0),'unnamed mutation advisory');
ok(P.gqLint(null).length===0,'lint null guard');
const stub=JSON.parse(P.gqVarStub(p));
ok(stub.id==='1','id stub');
ok(stub.first===10,'default applied to stub');
ok(JSON.parse(P.gqVarStub(P.gqParse('query Q($n: Int!) { a(n:$n) }'))).n===0,'int stub zero');
ok(JSON.parse(P.gqVarStub(P.gqParse('query Q($b: Boolean!) { a(b:$b) }'))).b===false,'bool stub false');
ok(Array.isArray(JSON.parse(P.gqVarStub(P.gqParse('query Q($l: [Int!]!) { a(l:$l) }'))).l),'list stub is array');
ok(JSON.parse(P.gqVarStub(P.gqParse('query Q($s: String!) { a(s:$s) }'))).s==='TODO_String','unknown scalar stub');
ok(P.gqVarStub(null)==='{}','stub null guard');
const c=P.gqCost(p);
ok(c.fields>0 && c.depth>0,'cost basics');
ok(['\u4f4e','\u4e2d','\u9ad8','\u5f88\u9ad8'].indexOf(c.level)>=0,'cost level label');
ok(P.gqCost(P.gqParse('{ a }')).level==='\u4f4e','shallow query low cost');
ok(P.gqCost(null).score===0,'cost null guard');
console.log('PASS '+n+' assertions');
