const { JSDOM } = require('C:/Users/53014/.workbuddy/binaries/node/workspace/node_modules/jsdom');
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true});
const {window}=dom; const errs=[]; window.addEventListener('error',e=>errs.push(e.message||String(e.error)));
setTimeout(()=>{ const doc=window.document; let pass=0,fail=0;
  const ok=(n,c)=>c?pass++:(fail++,console.error('  FAIL: '+n));
  ok('StegForgePure exposed', typeof window.StegForgePure==='object');
  ok('hide btn', !!doc.getElementById('hide'));
  doc.getElementById('hide').click();
  ok('hide injected', /已注入/.test(doc.getElementById('err').textContent));
  doc.getElementById('reveal').click();
  ok('reveal works', /codeword: nano-33/.test(doc.getElementById('out').textContent));
  ok('no js errors', errs.length===0);
  console.log('StegForge smoke: '+pass+' passed, '+fail+' failed');
  process.exit(fail?1:0);
}, 500);
