
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=/<script>([\s\S]*?)<\/script>/.exec(html);
const mod={exports:{}};
new Function('module','exports','require', m[1])(mod,mod.exports,require);
const P=mod.exports;
let pass=0,fail=0;
function ok(c,msg){ if(c){pass++;} else {fail++; console.error('FAIL: '+msg);} }
function has(t,sub,msg){ ok(String(t).indexOf(sub)>=0, msg+' ['+sub+']'); }

// ---- gen helpers ----
has(P.genHttps().join('\n'), 'RewriteRule', 'genHttps emits rule');
ok(P.genWww('add').length===3, 'genWww add 3 lines');
ok(P.genWww('remove').length===2, 'genWww remove 2 lines');
ok(P.genWww('none').length===0, 'genWww none empty');
has(P.genRedirect({type:'exact',from:'/a.html',to:'/b.html'}).join('\n'), 'RewriteRule ^a\\.html', 'genRedirect exact');
has(P.genRedirect({type:'prefix',from:'/blog',to:'/articles'}).join('\n'), 'RewriteRule', 'genRedirect prefix');
has(P.genRedirect({type:'regex',from:'^p/([0-9]+)$',to:'/x/$1'}).join('\n'), 'RewriteRule ^p/', 'genRedirect regex');
has(P.genSpa('/index.html').join('\n'), 'RewriteCond %{REQUEST_FILENAME} !-f', 'genSpa cond');
ok(P.genCache(null).join('\n').indexOf('ExpiresByType')>=0, 'genCache preset has types');
has(P.genGzip().join('\n'), 'AddOutputFilterByType DEFLATE', 'genGzip deflate');
var sec=P.genSecurity({hsts:true, hstsSub:true, csp:'default-src self'});
has(sec.join('\n'), 'Strict-Transport-Security', 'genSecurity hsts');
has(sec.join('\n'), 'Content-Security-Policy', 'genSecurity csp');
var cors=P.genCors({origin:'https://x.com'});
has(cors.join('\n'), 'Access-Control-Allow-Origin', 'genCors origin');
ok(P.genCors({}).length===0, 'genCors empty');
var hot=P.genHotlink({domains:['example.com'], extensions:['jpg']});
has(hot.join('\n'), 'RewriteRule', 'genHotlink rule');
var auth=P.genAuth({file:'/etc/.htpasswd', realm:'R'});
has(auth.join('\n'), 'AuthType Basic', 'genAuth');
ok(P.genAuth({}).length===0, 'genAuth empty');
var bip=P.genBlockIps(['1.2.3.4']);
has(bip.join('\n'), '<RequireAll>', 'genBlockIps wrapper');
has(bip.join('\n'), 'Require not ip 1.2.3.4', 'genBlockIps line');
var bag=P.genBlockAgents(['BadBot']);
has(bag.join('\n'), 'RewriteRule ^ - [F,L]', 'genBlockAgents rule');
var ep=P.genErrorPages({'404':'/404.html'});
has(ep.join('\n'), 'ErrorDocument 404 /404.html', 'genErrorPages');
var opt=P.genOptions({indexes:false});
has(opt.join('\n'), 'Options -Indexes', 'genOptions no indexes');
has(P.genOptions({indexes:true}).join('\n'), 'Options +Indexes', 'genOptions indexes');

// ---- build ----
var def=P.build({options:{indexes:false}});
has(def, 'Generated by HtaccessForge', 'build header');
has(def, 'Options -Indexes', 'build default options');

var full=P.build({
  https:true, www:'add', spa:'/index.html', gzip:true, cache:true,
  redirects:[{type:'exact',from:'/old',to:'/new'}],
  security:{hsts:true, frame:true, csp:'default-src self'},
  cors:{origin:'*'}, hotlink:{domains:['e.com'],extensions:['jpg']},
  auth:{file:'/etc/.htpasswd'}, blockIps:['1.1.1.1'], blockAgents:['BadBot'],
  errorPages:{'404':'/404.html'}
});
has(full, 'RewriteEngine On', 'build has engine');
has(full, 'RewriteRule ^(.*)$ https://%{HTTP_HOST}', 'build https');
has(full, 'RewriteRule ^(.*)$ https://www.%{HTTP_HOST}', 'build www add');
has(full, 'Strict-Transport-Security', 'build hsts');
has(full, 'Access-Control-Allow-Origin', 'build cors');
has(full, 'AddOutputFilterByType DEFLATE', 'build gzip');
has(full, 'ExpiresByType', 'build cache');
has(full, 'RewriteRule \\.(jpg', 'build hotlink');
has(full, 'AuthType Basic', 'build auth');
has(full, 'Require not ip 1.1.1.1', 'build blockIps');
has(full, 'ErrorDocument 404 /404.html', 'build errorPages');
ok(P.build({}).indexOf('RewriteEngine')<0, 'build empty no engine');

// ---- explain ----
ok(P.explain('RewriteEngine On')!=null, 'explain engine');
ok(P.explain('# comment')==='注释行', 'explain comment');
ok(P.explain('SomeUnknownDirective x')==null, 'explain unknown null');
ok(P.explain('Header always set X-Frame-Options "SAMEORIGIN"').indexOf('iframe')>=0, 'explain frame');
ok(P.explain('Options +FollowSymLinks').indexOf('符号链接')>=0, 'explain followsymlinks');
ok(P.explain('</IfModule>').indexOf('IfModule')>=0, 'explain closing ifmodule');
ok(P.explain('</FilesMatch>').indexOf('FilesMatch')>=0, 'explain closing filesmatch');
ok(P.explain('ServerSignature Off').indexOf('签名')>=0, 'explain serversignature');
ok(P.explain('Options -MultiViews')!=null, 'explain multiviews');
ok(P.explain('<Files "wp-login.php">')!=null, 'explain files block');
ok(P.explain('Redirect 301 /old /new').indexOf('/old')>=0, 'explain redirect alias');
ok(P.explain('AddType application/wasm .wasm').indexOf('wasm')>=0, 'explain addtype');
ok(P.explain('FileETag None')!=null, 'explain fileetag');
(function(){
  var maximal={
    options:{indexes:false, followSymlinks:true, dirIndex:'index.html index.php', charset:'UTF-8', protectDotfiles:true},
    https:true, www:'add', rewriteBase:'/',
    redirects:[{type:'exact',from:'/old',to:'/new'},{type:'prefix',from:'/blog',to:'/posts'},{type:'regex',from:'^/p/(\\d+)$',to:'/post/$1'}],
    blockAgents:['AhrefsBot','SemrushBot'],
    hotlink:{domains:['example.com'], extensions:['jpg','png','gif']},
    spa:'/index.html',
    security:{hsts:true, csp:"default-src 'self'", frame:'SAMEORIGIN'},
    cors:{origin:'*'},
    gzip:true, cache:true,
    blockIps:['1.2.3.4','10.0.0.0/8'],
    auth:{file:'/etc/apache2/.htpasswd', realm:'Restricted'},
    errorPages:{404:'/404.html', 500:'/500.html'}
  };
  var cfgs=[
    {https:true,www:'add',spa:true,gzip:true,cache:true,indexes:false,hsts:true},
    {options:{indexes:true, followSymlinks:false, protectDotfiles:false}, www:'remove'},
    maximal
  ];
  var miss=[];
  cfgs.forEach(function(c,i){
    P.build(c).split(/\r?\n/).forEach(function(l){
      var s=l.trim();
      if(s && s[0]!=='#' && P.explain(s)==null) miss.push('cfg'+i+': '+s);
    });
  });
  ok(miss.length===0, 'every generated line has an explanation, missing=' + miss.join(' | '));
  var mx=P.build(maximal);
  ok(mx.indexOf('AuthUserFile')>=0 && mx.indexOf('ErrorDocument 404')>=0 && mx.indexOf('Access-Control-Allow-Origin')>=0, 'maximal config emits all sections');
  ok(P.lint(mx).filter(function(x){ return x.level==='error'; }).length===0, 'maximal config lints clean');
})();

// ---- lint ----
var l1=P.lint('RewriteRule ^a$ /b [R=301,L]');
ok(l1.some(function(x){return x.level==='error' && x.msg.indexOf('RewriteEngine')>=0;}), 'lint rule before engine');
var l2=P.lint('Order allow,deny\nDeny from all');
ok(l2.some(function(x){return x.level==='error' && x.msg.indexOf('2.2')>=0;}), 'lint 2.2 syntax');
var l3=P.lint('Options +Indexes');
ok(l3.some(function(x){return x.level==='warn' && x.msg.indexOf('目录列表')>=0;}), 'lint +Indexes');
var l4=P.lint('<IfModule x.c>\nRewriteEngine On');
ok(l4.some(function(x){return x.level==='error' && x.msg.indexOf('没有闭合')>=0;}), 'lint unclosed tag');
var l5=P.lint('RewriteEngine On\nRewriteRule ^a$ /b [R=301]');
ok(l5.some(function(x){return x.msg.indexOf('L 标志')>=0;}), 'lint missing L');

// ---- stats ----
var st=P.stats('RewriteEngine On\nRewriteRule ^a$ /b\nHeader set X x\n# c');
ok(st.total===4, 'stats total');
ok(st.directives===3, 'stats directives');
ok(st.rules===1, 'stats rules');
ok(st.headers===1, 'stats headers');
ok(st.comments===1, 'stats comments');
ok(st.blank===0, 'stats blank');

console.log('PASS '+pass+' / FAIL '+fail);
if(fail>0) process.exit(1);
