
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
ok(P.jlParse('').error!==null,'empty error');
ok(P.jlParse('{bad}').error!==null,'bad json error');
ok(P.jlParse('"str"').error!==null,'non object error');
ok(P.jlParse('{"a":1}').error===null,'valid json');
ok(P.jlParse('<script type="application/ld+json">{"a":1}<\/script>').data.a===1,'strips script tag');
ok(P.jlNodes({'@type':'X'}).length===1,'nodes single');
ok(P.jlNodes([{a:1},{b:2}]).length===2,'nodes array');
ok(P.jlNodes({'@graph':[{a:1},{b:2},{c:3}]}).length===3,'nodes graph');
const good={'@context':'https://schema.org','@type':'Article',headline:'h',author:'a',datePublished:'2026-07-31',
  image:'i',description:'d',dateModified:'2026-07-31',publisher:'p'};
const v=P.jlValidate(good);
ok(v.valid===true && v.errors.length===0,'valid article');
ok(v.warns.length===0,'no warnings when complete');
ok(v.types[0]==='Article','type captured');
ok(v.nodes===1,'node count');
const missing=P.jlValidate({'@context':'https://schema.org','@type':'Article',headline:'h'});
ok(missing.valid===false,'missing required invalid');
ok(missing.errors.some(e=>e.indexOf('author')>=0),'missing author reported');
ok(missing.warns.some(w=>w.indexOf('image')>=0),'recommended image warned');
ok(P.jlValidate({'@type':'Article',headline:'h',author:'a',datePublished:'x'}).errors.some(e=>e.indexOf('@context')>=0),'missing context error');
ok(P.jlValidate({'@context':'http://example.com','@type':'Organization',name:'n'}).warns.some(w=>w.indexOf('schema.org')>=0),'non schema context warned');
ok(P.jlValidate({'@context':'https://schema.org'}).errors.some(e=>e.indexOf('@type')>=0),'missing type error');
ok(P.jlValidate({'@context':'https://schema.org','@type':'ZzzUnknown'}).warns.some(w=>w.indexOf('ZzzUnknown')>=0),'unknown type warned');
ok(P.jlValidate({'@context':'https://schema.org','@type':['Article','Thing'],headline:'h',author:'a',datePublished:'2026-01-01'}).types[0]==='Article','array type uses first');
ok(P.jlDateOk('2026-07-31'),'date ok simple');
ok(P.jlDateOk('2026-07-31T10:00:00Z'),'date ok iso z');
ok(P.jlDateOk('2026-07-31T10:00:00+08:00'),'date ok offset');
ok(!P.jlDateOk('31/07/2026'),'date reject slash');
ok(!P.jlDateOk('2026-7-1'),'date reject unpadded');
ok(P.jlDateIssues(good).length===0,'no date issues');
ok(P.jlDateIssues({'@type':'Article',datePublished:'yesterday'}).length===1,'date issue detected');
ok(P.jlDateIssues({'@type':'Event',startDate:'bad',endDate:'2026-01-01'}).length===1,'only bad date reported');
const built=P.jlBuild('Product',{name:'x',sku:'s1',ignored:'no'});
ok(built['@type']==='Product' && built['@context']==='https://schema.org','build headers');
ok(built.name==='x' && built.sku==='s1','build keeps known fields');
ok(built.ignored===undefined,'build drops unknown field');
ok(Object.keys(P.jlBuild('Product',{})).length===2,'build empty fields');
const st=P.jlStats(good);
ok(st.nodes===1 && st.fields===9,'stats fields');
ok(st.bytes>0 && st.depth>=1,'stats bytes and depth');
ok(P.jlStats({'@graph':[{a:1},{b:2}]}).nodes===2,'stats graph nodes');
ok(P.jlStats({a:{b:{c:1}}}).depth===3,'stats nested depth');
const emb=P.jlEmbed({a:1});
ok(emb.indexOf('application/ld+json')>=0,'embed mime');
ok(emb.indexOf('"a": 1')>=0,'embed pretty printed');
console.log('PASS '+n+' assertions');
