/* Node test: extract first <script> from index.html, run pure fns, assert. */
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const html = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8');
const m = html.match(/<script>([\s\S]*?)<\/script>/);
if (!m) { console.error('NO SCRIPT FOUND'); process.exit(1); }
const fn = new Function('module', 'exports', 'require', m[1]);
fn(module, module.exports, require);
const A = module.exports;

let pass = 0, fail = 0;
function ok(name, cond){ if (cond) pass++; else { fail++; console.error('  FAIL: ' + name); } }

ok('available has Node', A.available().indexOf('Node') >= 0);
ok('available count', A.available().length >= 15);
ok('combine Node', A.combine(['Node']).indexOf('node_modules/') >= 0);
ok('combine macOS', A.combine(['macOS']).indexOf('.DS_Store') >= 0);
ok('combine multi', (() => { var t=A.combine(['Node','macOS']); return t.indexOf('node_modules/')>=0 && t.indexOf('.DS_Store')>=0; })());
ok('combine header', A.combine(['Node']).indexOf('Generated by GitignoreForge') >= 0);
ok('combine unknown ignored', A.combine(['Node','Nope']).indexOf('Nope') < 0);
ok('combine empty hint', A.combine([]).indexOf('选择上方模板') >= 0);

console.log('GitignoreForge _test: ' + pass + ' passed, ' + fail + ' failed');
process.exit(fail ? 1 : 0);
