
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
ok(P.sha256Hex('')==='e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'sha256 empty vector');
ok(P.sha256Hex('abc')==='ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad', 'sha256 abc vector');
ok(P.sha256Hex('abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq')==='248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1', 'sha256 448bit vector');
ok(P.sha256B64('')==='47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=', 'sha256 empty base64');
ok(P.sha256B64('abc').length===44, 'sha256 base64 length 44');
ok(P.sha256Hex('hello')!==P.sha256Hex('hellp'), 'sha256 avalanche');
ok(P.utf8Bytes('abc').length===3, 'utf8 ascii bytes');
ok(P.utf8Bytes('中').length===3, 'utf8 cjk three bytes');
ok(P.utf8Bytes('\u00e9').length===2, 'utf8 latin1 two bytes');
ok(P.sha256Hex('\u4e2d\u6587').length===64, 'sha256 handles cjk');
ok(P.bytesToHex([0,255,16])==='00ff10', 'bytesToHex padding');
ok(P.bytesToB64([77,97,110])==='TWFu', 'base64 no padding');
ok(P.bytesToB64([77,97])==='TWE=', 'base64 one pad');
ok(P.bytesToB64([77])==='TQ==', 'base64 two pads');
var bi=P.buildIntegrity('console.log(1);','sha256');
ok(bi.value.indexOf('sha256-')===0, 'buildIntegrity prefix');
ok(bi.error===null, 'buildIntegrity sha256 no error');
ok(P.buildIntegrity('x','sha384').error!==null, 'sha384 not computed locally');
ok(P.buildIntegrity('x','sha384').command.indexOf('sha384')>-1, 'sha384 fallback command');
ok(P.opensslCommand('a.js','sha512').indexOf('-sha512')>-1, 'openssl command sha512');
var pl=P.parseIntegrity('sha256-'+P.sha256B64('x'));
ok(pl.length===1 && pl[0].valid===true, 'parseIntegrity valid sha256');
ok(pl[0].strength===1, 'sha256 strength 1');
ok(P.parseIntegrity('sha384-'+'A'.repeat(64))[0].valid===true, 'sha384 length accepted');
ok(P.parseIntegrity('sha512-'+'A'.repeat(88))[0].valid===true, 'sha512 length accepted');
ok(P.parseIntegrity('sha256-abc')[0].valid===false, 'wrong length rejected');
ok(P.parseIntegrity('md5-'+'A'.repeat(44))[0].error.indexOf('不支持')>-1, 'md5 unsupported');
ok(P.parseIntegrity('nohyphen')[0].error.indexOf('算法前缀')>-1, 'missing prefix flagged');
ok(P.parseIntegrity('sha256-!!!!')[0].valid===false, 'non base64 rejected');
var two=P.parseIntegrity('sha256-'+'A'.repeat(44)+' sha512-'+'B'.repeat(88));
ok(two.length===2, 'multiple digests parsed');
ok(P.strongest(two).algo==='sha512', 'strongest picks sha512');
ok(P.strongest(P.parseIntegrity('bad'))===null, 'strongest null when none valid');
var good=P.verifyIntegrity('payload','sha256-'+P.sha256B64('payload'));
ok(good.ok===true, 'verifyIntegrity match');
ok(P.verifyIntegrity('payload','sha256-'+P.sha256B64('other')).ok===false, 'verifyIntegrity mismatch');
ok(P.verifyIntegrity('x','').ok===false, 'verifyIntegrity empty attr');
ok(P.verifyIntegrity('x','sha512-'+'A'.repeat(88)).ok===null, 'verifyIntegrity sha512 not local');
var t=P.buildTag({url:'https://cdn.x/a.js', integrity:'sha384-AAA', defer:true});
ok(t.kind==='script', 'buildTag script kind');
ok(t.tag.indexOf('integrity="sha384-AAA"')>-1, 'buildTag integrity attr');
ok(t.tag.indexOf('crossorigin="anonymous"')>-1, 'buildTag default crossorigin');
ok(t.tag.indexOf('defer')>-1, 'buildTag defer');
var st=P.buildTag({url:'https://cdn.x/a.css', integrity:'sha384-AAA'});
ok(st.kind==='style', 'buildTag detects css');
ok(st.tag.indexOf('rel="stylesheet"')>-1, 'buildTag link rel');
var a1=P.auditTag('<script src="https://cdn.x/a.js"></script>');
ok(a1.errors>=1, 'cross origin without integrity is error');
var a2=P.auditTag('<script src="https://cdn.x/a.js" integrity="sha256-'+'A'.repeat(44)+'"></script>');
ok(a2.errors>=1, 'integrity without crossorigin is error');
var a3=P.auditTag('<script src="https://cdn.x/a.js" integrity="sha384-'+'A'.repeat(64)+'" crossorigin="anonymous"></script>');
ok(a3.ok===true, 'well formed tag passes');
ok(P.auditTag('<script src="http://cdn.x/a.js" integrity="sha384-'+'A'.repeat(64)+'" crossorigin></script>').errors>=1, 'http url flagged');
ok(P.auditTag('<script src="https://x/a.js" integrity="sha256-'+'A'.repeat(44)+'" crossorigin></script>').warnings>=1, 'sha256 suggests upgrade');
ok(P.auditTag('<div></div>').errors===1, 'non tag rejected');
ok(P.auditTag('<script src="https://x/a.js" integrity="sha384-'+'A'.repeat(64)+'" crossorigin="bogus"></script>').errors>=1, 'bad crossorigin value');
console.log('SriForge _test: '+n+' passed, 0 failed');
