const { JSDOM } = require('C:/Users/53014/.workbuddy/binaries/node/workspace/node_modules/jsdom');
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true});
const {window}=dom; const errs=[]; window.addEventListener('error',e=>errs.push(e.message));
setTimeout(()=>{ const doc=window.document; let pass=0,fail=0;
  const ok=(n,c)=>c?pass++:(fail++,console.error('  FAIL: '+n));
  ok('JwtForgePure exposed', typeof window.JwtForgePure==='object');
  ok('run btn', !!doc.getElementById('run'));
  // construct a token in-page using the pure API
  var P=window.JwtForgePure;
  var tok = P.b64urlEncode(JSON.stringify({alg:'HS256',typ:'JWT'}))+'.'+P.b64urlEncode(JSON.stringify({sub:'1',name:'Ada',exp:9999999999}))+'.sig';
  doc.getElementById('tok').value=tok; doc.getElementById('run').click();
  var out=doc.getElementById('out').textContent;
  ok('output produced', out.length>0 && out.indexOf('PAYLOAD')>=0);
  ok('shows unsigned alg', out.indexOf('HS256')>=0);
  ok('no js errors', errs.length===0);
  if(errs.length) console.error('  js errors:',errs);
  console.log('JwtForge smoke: '+pass+' passed, '+fail+' failed');
  process.exit(fail?1:0);
},400);
