
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
ok(P.fgParseFolded('').error!==null,'empty error');
ok(P.fgParseFolded('garbage').error!==null,'garbage error');
const r=P.fgParseFolded('a;b 10\na;c 5\n# note\nbadline\n');
ok(r.error===null && r.rows.length===2,'parse two rows');
ok(r.bad===1,'bad line counted');
ok(r.rows[0].frames.length===2 && r.rows[0].value===10,'row content');
ok(P.fgParseFolded('a 1.5').rows[0].value===1.5,'float value');
ok(P.fgParseFolded('a; ;b 3').rows[0].frames.length===2,'empty frame dropped');
const root=P.fgBuild(r.rows);
ok(root.value===15,'root total');
ok(root.children.a.value===15,'branch aggregated');
ok(root.children.a.children.b.value===10,'leaf value');
ok(root.children.a.children.b.self===10,'leaf self');
ok(root.children.a.self===undefined,'internal node no self');
ok(root.children.a.depth===1 && root.children.a.children.c.depth===2,'depths assigned');
const flat=P.fgFlatten(root);
ok(flat[0].name==='root' && flat[0].x===0,'flatten root first');
ok(flat.length===4,'flatten node count');
ok(flat[2].name==='b','flatten orders by value desc');
ok(flat[3].x===10,'sibling x offset');
ok(flat.every(f=>f.x>=0),'no negative x');
const s=P.fgStats(root, flat);
ok(s.total===15 && s.frames===3,'stats total and frames');
ok(s.maxDepth===2 && s.leaves===2,'stats depth and leaves');
const tops=P.fgSelfTop(flat,5);
ok(tops.length===2 && tops[0].name==='b','self top order');
ok(P.fgSelfTop(flat,1).length===1,'self top k limit');
ok(tops.every(t=>t.depth>0),'self top excludes root');
const hp=P.fgHotPath(root);
ok(hp.length===2 && hp[0].name==='a' && hp[1].name==='b','hot path');
ok(P.fgHotPath({children:{}}).length===0,'hot path leaf root');
ok(P.fgColor('abc')===P.fgColor('abc'),'color deterministic');
ok(/^hsl\(\d+,\d+%,\d+%\)$/.test(P.fgColor('main')),'color format');
ok(P.fgColor('a')!==P.fgColor('bbbb'),'color varies');
ok(P.fgPercent(5,10)==='50.00%','percent');
ok(P.fgPercent(1,3)==='33.33%','percent rounding');
ok(P.fgPercent(1,0)==='0.00%','percent zero guard');
const deep=P.fgBuild(P.fgParseFolded('x;y;z;w 4').rows);
ok(P.fgStats(deep, P.fgFlatten(deep)).maxDepth===4,'deep stack depth');
console.log('PASS '+n+' assertions');
