
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
ok(P.hmParseDate('2026-07-30')!==null,'parse valid date');
ok(P.hmParseDate('2026-13-01')===null,'reject month 13');
ok(P.hmParseDate('2026-02-30')===null,'reject feb 30');
ok(P.hmParseDate('bad')===null,'reject garbage');
ok(P.hmParseDate('2024-02-29')!==null,'leap day valid');
ok(P.hmFmtDate(P.hmParseDate('2026-01-05'))==='2026-01-05','fmt roundtrip');
ok(P.hmFmtDate(P.hmParseDate('2026-1-5'))==='2026-01-05','fmt pads');
ok(P.hmParse('').error!==null,'empty parse error');
ok(P.hmParse('nope').error!==null,'invalid parse error');
const r=P.hmParse('2026-07-01 3\n2026-07-02\n2026-07-01 2\n#c\nxx');
ok(r.error===null,'parse ok');
ok(r.map['2026-07-01']===5,'same day summed');
ok(r.map['2026-07-02']===1,'default value one');
ok(r.bad===1,'bad counted');
ok(r.count===3,'count records');
const rg=P.hmRange(r.map);
ok(rg.first==='2026-07-01' && rg.last==='2026-07-02','range');
ok(rg.days===2,'range days');
const g=P.hmGrid(r.map,'2026-07-01','2026-07-14');
ok(g.error===null,'grid ok');
ok(g.weeks.length>=2,'grid weeks');
ok(g.weeks[0].length===7,'grid column is a week');
ok(g.weeks[0].some(c=>c.value===null),'pre-range padded null');
ok(P.hmGrid(r.map,'2026-07-14','2026-07-01').error!==null,'grid reversed error');
ok(P.hmGrid(r.map,'bad','2026-07-01').error!==null,'grid invalid date error');
let found=false;
g.weeks.forEach(w=>w.forEach(c=>{ if(c.date==='2026-07-01' && c.value===5) found=true; }));
ok(found,'grid carries value');
const cuts=P.hmLevels({a:1,b:2,c:3,d:4},4);
ok(cuts.length===4,'levels bucket count');
ok(cuts[0]<=cuts[3],'levels ascending');
ok(P.hmLevels({},4).length===0,'levels empty');
ok(P.hmLevelOf(0,cuts)===0,'level zero');
ok(P.hmLevelOf(null,cuts)===-1,'level null');
ok(P.hmLevelOf(1,cuts)===1,'level one');
ok(P.hmLevelOf(999,cuts)===4,'level max');
const sk=P.hmStreak({'2026-07-01':1,'2026-07-02':1,'2026-07-04':1},'2026-07-01','2026-07-04');
ok(sk.best===2,'streak best');
ok(sk.current===1,'streak current');
ok(sk.active===3,'streak active days');
ok(P.hmStreak({}, 'bad','x').best===0,'streak guard');
const st=P.hmStats(r.map);
ok(st.total===6 && st.days===2,'stats total');
ok(st.max===5 && st.maxDate==='2026-07-01','stats max');
ok(st.avg===3,'stats avg');
ok(P.hmStats({}).days===0,'stats empty');
console.log('PASS '+n+' assertions');
