
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
const H='<!doctype html><html lang="zh-CN"><head><title>示例页面：一个收录数百款零依赖单文件工具的开发者实用集合站点</title><meta name="description" content="这是一个用于演示 SEO 分析的示例页面，包含完整的 Open Graph 与 JSON-LD 结构化元数据，便于社交分享、爬虫理解与搜索引擎优化，单文件零依赖本地优先。"><meta property="og:title" content="示例"><meta property="og:description" content="演示用示例页面"><meta property="og:image" content="https://x.com/a.png"><link rel="canonical" href="https://x.com/p"><meta name="viewport" content="width=1"><script type="application/ld+json">{}</script></head><body><h1>标题</h1><h2>x</h2><p>body</p></body></html>';
const meta=P.seoExtractMeta(H);
ok(meta.title.indexOf('示例页面')>=0,'title extracted');
ok(meta.description.indexOf('演示')>=0,'description extracted');
ok(meta.og_title==='示例','og:title');
ok(meta.og_image==='https://x.com/a.png','og:image');
ok(meta.canonical==='https://x.com/p','canonical');
ok(meta.viewport==='width=1','viewport');
ok(meta.jsonld===1,'jsonld count');
ok(meta.h1===1,'h1 count');
ok(meta.h2===1,'h2 count');
ok(meta.lang==='zh-CN','lang');
const H2='<title>短</title><meta name="description" content="太短"><meta property="og:image" content="x">';
const s2=P.seoScore(P.seoExtractMeta(H2));
ok(s2.score < 100,'weak page low score');
ok(s2.checks.length===12,'12 checks');
const s1=P.seoScore(meta);
ok(s1.score===100,'full page 100');
ok(P.seoLen('abc')===3,'len');
ok(P.seoLen('')===0,'len empty');
const stripped=P.seoStripTags('<p>hello <b>world</b></p>');
ok(stripped.indexOf('<')<0,'strip tags removes <');
ok(P.seoStripTags('<script>bad()</script>text').indexOf('bad')<0,'strip script');
const kw=P.seoKeywordDensity('the cat and the dog and the cat', 5);
ok(kw[0].word==='the' && kw[0].count===3,'kw top count');
ok(kw.length<=5,'kw topN clamp');
const kw2=P.seoKeywordDensity('', 5);
ok(kw2.length===0,'kw empty');
const kw3=P.seoKeywordDensity('a b c a b', 10);
ok(kw3.every(function(x){return x.density>0;}),'kw density positive');
console.log('PASS '+n+' assertions');
