const { JSDOM } = require('C:/Users/53014/.workbuddy/binaries/node/workspace/node_modules/jsdom');
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true});
const {window}=dom; const errs=[]; window.addEventListener('error',e=>errs.push(e.message||String(e.error)));
setTimeout(()=>{ const doc=window.document; let pass=0,fail=0;
  const ok=(n,c)=>c?pass++:(fail++,console.error('  FAIL: '+n));
  ok('NumeralForgePure exposed', typeof window.NumeralForgePure==='object');
  ok('en btn', !!doc.getElementById('en'));
  doc.getElementById('cn').click();
  ok('cn output capital', /\u5143/.test(doc.getElementById('out').textContent));
  ok('no js errors', errs.length===0);
  console.log('NumeralForge smoke: '+pass+' passed, '+fail+' failed');
  process.exit(fail?1:0);
}, 500);
