
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
var ps=P.parseParamLines('q | string | kw | yes\nk | integer | num | no\ns | string | sc | no | a,b');
ok(ps.length===3, 'parse 3 params');
ok(ps[0].required===true && ps[1].required===false, 'required flag parsed');
ok(ps[2]['enum'].length===2, 'enum parsed');
ok(P.parseParamLines('# comment\n\nx | string').length===1, 'comments and blanks skipped');
var s1=P.buildSchema('t','desc',ps,'openai');
ok(s1.type==='function' && s1['function'].name==='t', 'openai style shape');
ok(s1['function'].parameters.required.length===1, 'openai required list');
ok(s1['function'].parameters.additionalProperties===false, 'additionalProperties false');
var s2=P.buildSchema('t','desc',ps,'anthropic');
ok(!!s2.input_schema && !s2.parameters, 'anthropic uses input_schema');
var s3=P.buildSchema('t','desc',ps,'mcp');
ok(!!s3.inputSchema, 'mcp uses inputSchema');
ok(P.buildSchema('t','d',[{name:'a',type:'array',required:false}],'mcp').inputSchema.properties.a.items.type==='string', 'array gets items');
ok(P.lintSchema('good_name','a sufficiently long description',ps).valid===true, 'lint passes');
ok(P.lintSchema('','desc',ps).valid===false, 'empty name fails');
ok(P.lintSchema('bad name','desc',ps).valid===false, 'space in name fails');
ok(P.lintSchema('t','x',ps).warnings.length>0, 'short description warns');
ok(P.lintSchema('t','long enough description here',[{name:'a',type:'string',description:'d'},{name:'a',type:'string',description:'d'}]).valid===false, 'duplicate param name fails');
ok(P.lintSchema('t','long enough description here',[{name:'1bad',type:'string',description:'d'}]).valid===false, 'illegal param name fails');
ok(P.lintSchema('t','long enough description here',[{name:'a',type:'weird',description:'d'}]).valid===false, 'unknown type fails');
ok(P.schemaTokenCost(s1).approxTokens>0, 'token cost positive');
var f=s1['function'];
ok(P.validateCall(f,{q:'x'}).valid===true, 'valid call passes');
ok(P.validateCall(f,{}).valid===false, 'missing required fails');
ok(P.validateCall(f,{q:'x',zzz:1}).valid===false, 'undeclared param fails');
ok(P.validateCall(f,{q:'x',k:1.5}).valid===false, 'non-integer fails');
ok(P.validateCall(f,{q:'x',k:3}).valid===true, 'integer ok');
ok(P.validateCall(f,{q:'x',s:'zzz'}).valid===false, 'enum violation fails');
ok(P.validateCall(f,{q:123}).valid===false, 'wrong type fails');
ok(P.validateCall({},{}).valid===false, 'unresolvable schema fails');
console.log('AgentSchemaForge _test: '+n+' passed, 0 failed');
