
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
ok(P.trIndentWidth('  a')===2,'indent spaces');
ok(P.trIndentWidth('\ta')===4,'indent tab is four');
ok(P.trIndentWidth('a')===0,'indent zero');
ok(P.trIndentWidth('\t  a')===6,'indent mixed');
ok(P.trParseIndent('').error!==null,'empty error');
ok(P.trParseIndent('   \n\n').error!==null,'blank error');
const r=P.trParseIndent('a\n  b\n  c\n    d\ne');
ok(r.error===null && r.count===5,'parse count');
ok(r.root.children.length===2,'two top level');
ok(r.root.children[0].name==='a','first node');
ok(r.root.children[0].children.length===2,'a has two children');
ok(r.root.children[0].children[1].children[0].name==='d','deep nesting');
ok(r.root.children[1].name==='e','sibling after dedent');
const glyph=P.trParseIndent('src\n\u251c\u2500\u2500 a.ts\n\u2514\u2500\u2500 b.ts');
ok(glyph.root.children[0].children.length===2,'tree glyph input parsed');
const st=P.trStats(r.root);
ok(st.total===5,'stats total');
ok(st.dirs===2 && st.files===3,'stats dirs and files');
ok(st.maxDepth===3,'stats depth');
ok(P.trStats({children:[]}).total===0,'stats empty');
const rendered=P.trRender(r.root,false);
ok(rendered.indexOf('\u251c\u2500\u2500 a/')>=0,'render unicode tee');
ok(rendered.indexOf('\u2514\u2500\u2500 e')>=0,'render unicode last');
const ascii=P.trRender(r.root,true);
ok(ascii.indexOf('|-- a/')>=0,'render ascii tee');
ok(ascii.indexOf('`-- e')>=0,'render ascii last');
ok(ascii.indexOf('\u2502')<0,'ascii mode has no unicode bars');
ok(P.trRender({children:[]},false)==='','render empty tree');
const j=P.trToJson(r.root);
ok(j.a && j.a.b===null,'json leaf null');
ok(j.a.c && j.a.c.d===null,'json nested');
ok(j.e===null,'json sibling leaf');
ok(Object.keys(P.trToJson({children:[]})).length===0,'json empty object');
const back=P.trFromJson({x:{y:null},z:null});
ok(back.children.length===2 && back.children[0].name==='x','fromJson keys');
ok(back.children[0].children[0].name==='y','fromJson nested');
ok(P.trFromJson({arr:[1,2]}).children[0].children.length===2,'fromJson array');
ok(P.trRender(P.trFromJson(j),false)===rendered,'json roundtrip renders same');
const paths=P.trPaths(r.root);
ok(paths.indexOf('a/')>=0 && paths.indexOf('a/c/d')>=0,'paths list');
ok(paths.length===5,'paths count');
const fp=P.trFromPaths('src/a.ts\nsrc/b.ts\nREADME.md');
ok(fp.error===null && fp.root.children.length===2,'fromPaths roots');
ok(fp.root.children[0].children.length===2,'fromPaths merges shared prefix');
ok(P.trFromPaths('').error!==null,'fromPaths empty error');
ok(P.trFromPaths('./x/y').root.children[0].name==='x','fromPaths strips leading dot slash');
ok(P.trStats(fp.root).total===4,'fromPaths stats');
ok(P.trStats(fp.root).dirs===1 && P.trStats(fp.root).files===3,'fromPaths dir and leaf split');
console.log('PASS '+n+' assertions');
