const { JSDOM } = require('C:/Users/53014/.workbuddy/binaries/node/workspace/node_modules/jsdom');
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true});
const {window}=dom; const errs=[]; window.addEventListener('error',e=>errs.push(e.message));
setTimeout(()=>{ const doc=window.document; let pass=0,fail=0;
  const ok=(n,c)=>c?pass++:(fail++,console.error('  FAIL: '+n));
  ok('KeyForgePure exposed', typeof window.KeyForgePure==='object');
  ok('lookup output', (doc.getElementById('out').textContent||'').indexOf('Enter')>=0);
  doc.getElementById('lookup').value='27'; doc.getElementById('run').click();
  ok('lookup escape', (doc.getElementById('out').textContent||'').indexOf('Escape')>=0);
  const ev=new window.KeyboardEvent('keydown',{key:'a',code:'KeyA',ctrlKey:true,bubbles:true});
  window.dispatchEvent(ev);
  ok('keydown shown', (doc.getElementById('bigkey').textContent||'').indexOf('a')>=0);
  ok('no js errors', errs.length===0);
  if(errs.length) console.error('  js errors:',errs);
  console.log('KeyForge smoke: '+pass+' passed, '+fail+' failed');
  process.exit(fail?1:0);
},400);
