
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
ok(P.parseMaxAge('600').value===600, 'parseMaxAge plain seconds');
ok(P.parseMaxAge('7d').value===604800, 'parseMaxAge days');
ok(P.parseMaxAge('2h').value===7200, 'parseMaxAge hours');
ok(P.parseMaxAge('1 year').value===31536000, 'parseMaxAge year word');
ok(P.parseMaxAge('abc').error!==null, 'parseMaxAge rejects garbage');
ok(P.formatAge(0)==='0s', 'formatAge zero');
ok(P.formatAge(90)==='1m 30s', 'formatAge minute+second');
ok(P.formatAge(86400)==='1d', 'formatAge single day');
var h=P.buildHeader({visibility:'public',maxAge:31536000,immutable:true});
ok(h.value==='public, max-age=31536000, immutable', 'buildHeader immutable static');
ok(h.warnings.length===0, 'immutable with long max-age no warning');
ok(P.buildHeader({noStore:true}).value==='no-store', 'buildHeader no-store short circuit');
ok(P.buildHeader({noStore:true,maxAge:60}).warnings.length===1, 'no-store plus max-age warns');
ok(P.buildHeader({visibility:'private',sMaxAge:60}).warnings.length===1, 'private plus s-maxage warns');
ok(P.buildHeader({visibility:'public',maxAge:10,immutable:true}).warnings.length===1, 'immutable short max-age warns');
ok(P.buildHeader({}).value==='no-cache', 'buildHeader empty defaults to no-cache');
var p=P.parseHeader('Cache-Control: public, max-age=60, s-maxage=300, immutable');
ok(p.directives['max-age']===60, 'parseHeader numeric directive');
ok(p.directives.immutable===true, 'parseHeader boolean directive');
ok(p.list.length===4, 'parseHeader token count');
ok(P.parseHeader('public, surrogate-control').unknown.length===1, 'parseHeader flags unknown token');
ok(P.freshness({age:10,maxAge:60}).state==='fresh', 'freshness fresh');
ok(P.freshness({age:10,maxAge:60}).remaining===50, 'freshness remaining seconds');
ok(P.freshness({age:100,maxAge:60}).state==='stale', 'freshness stale');
ok(P.freshness({age:100,maxAge:60,staleWhileRevalidate:120}).state==='stale-revalidating', 'freshness swr window');
ok(P.freshness({age:300,maxAge:60,staleWhileRevalidate:120}).state==='stale', 'freshness past swr window');
ok(P.freshness({age:10}).state==='unknown', 'freshness without max-age');
ok(P.preset('static-hashed').opt.immutable===true, 'preset static hashed');
ok(P.preset('sensitive').opt.noStore===true, 'preset sensitive no-store');
ok(P.preset('nope')===null, 'unknown preset returns null');
var e1=P.etagFor('hello'), e2=P.etagFor('hello'), e3=P.etagFor('hellp');
ok(e1===e2, 'etagFor deterministic');
ok(e1!==e3, 'etagFor differs on change');
ok(/^"[0-9a-f]{16}"$/.test(e1), 'etagFor format');
ok(P.etagFor('x',true).indexOf('W/')===0, 'etagFor weak prefix');
ok(P.etagMatch('"abc"','"abc"')===true, 'etagMatch exact');
ok(P.etagMatch('*','"abc"')===true, 'etagMatch wildcard');
ok(P.etagMatch('"a", "b"','"b"')===true, 'etagMatch list');
ok(P.etagMatch('W/"a"','"a"')===true, 'etagMatch weak comparison');
ok(P.etagMatch('','"a"')===false, 'etagMatch empty');
var a=P.auditHeader('public, private, max-age=60');
ok(a.errors===1, 'audit public+private is error');
ok(P.auditHeader('public, max-age=60, no-store').warnings>=1, 'audit no-store conflict');
ok(P.auditHeader('public, max-age=31536000, immutable').ok===true, 'audit clean header');
ok(P.auditHeader('public').warnings>=1, 'audit missing freshness warns');
console.log('HttpCacheForge _test: '+n+' passed, 0 failed');
