
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
ok(P.atTokenize('a b c').length===3,'tokenize splits');
ok(P.atTokenize('  ').length===0,'tokenize empty');
ok(P.atTokenize('hi, there').join('|')==='hi|,|there','tokenize punctuation split');
ok(P.atTokenize('don\'t').length===1,'tokenize keeps apostrophe');
ok(P.atHash('a',0)>=0 && P.atHash('a',0)<1,'hash in unit range');
ok(P.atHash('a',0)===P.atHash('a',0),'hash deterministic');
ok(P.atHash('a',0)!==P.atHash('a',1),'hash seed sensitive');
const e=P.atEmbed('cat',8,0);
ok(e.length===8,'embed dim');
ok(e.every(x=>x>=-1&&x<=1),'embed range');
ok(P.atDot([1,2],[3,4])===11,'dot product');
const sm=P.atSoftmax([1,1,1]);
ok(Math.abs(sm.reduce((a,b)=>a+b,0)-1)<1e-9,'softmax sums to one');
ok(Math.abs(sm[0]-1/3)<1e-9,'softmax uniform');
ok(P.atSoftmax([]).length===0,'softmax empty');
ok(P.atSoftmax([1000,1000])[0]===0.5,'softmax numerically stable');
const toks=['a','b','c'];
const rows=P.atScores(toks,0,8,false);
ok(rows.length===3 && rows[0].length===3,'scores shape');
ok(rows.every(r=>Math.abs(r.reduce((a,b)=>a+b,0)-1)<1e-9),'each row sums to one');
const cz=P.atScores(toks,0,8,true);
ok(cz[0][1]<1e-6 && cz[0][2]<1e-6,'causal masks future');
ok(Math.abs(cz[0][0]-1)<1e-6,'causal first row all self');
ok(cz[2][0]>0 && cz[2][1]>0,'causal keeps past');
ok(P.atScores(toks,1,8,false)[0][1]!==rows[0][1],'different head differs');
ok(P.atRowEntropy([1,0,0])===0,'entropy of one-hot is zero');
ok(P.atRowEntropy([0.5,0.5])===1,'entropy of pair is one');
ok(P.atRowEntropy([0.25,0.25,0.25,0.25])===2,'entropy of four');
const tk=P.atTopK([0.1,0.7,0.2],toks,2);
ok(tk.length===2 && tk[0].token==='b','topk sorted');
ok(tk[1].token==='c','topk second');
ok(P.atTopK([0.5,0.5],['x','y'],5).length===2,'topk clamps to length');
const s=P.atSummary(rows,toks);
ok(s.error===null && s.tokens===3,'summary tokens');
ok(s.avgEntropy>=0 && s.avgEntropy<=s.maxEntropy+1e-9,'entropy within max');
ok(Math.abs(s.maxEntropy-Math.round(Math.log(3)/Math.LN2*1000)/1000)<1e-9,'max entropy log2 n');
ok(s.selfWeight>0 && s.selfWeight<=1,'self weight range');
ok(toks.indexOf(s.focusToken)>=0,'focus token from set');
ok(P.atSummary([],[]).error!==null,'summary empty error');
ok(P.atCell(0.5).alpha===0.5,'cell alpha');
ok(P.atCell(2).alpha===1,'cell clamps high');
ok(P.atCell(-1).alpha===0,'cell clamps low');
ok(P.atCell(0.123).label==='12.3%','cell label');
console.log('PASS '+n+' assertions');
