
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const m=html.match(/<script>([\s\S]*?)<\/script>/);
const mod={exports:{}};
new Function('module','exports','require',m[1])(mod,mod.exports,require);
const P=mod.exports;
let n=0; function ok(c,msg){ if(!c){ console.error('FAIL: '+msg); process.exit(1);} n++; }
ok(P.isIPv4('93.184.216.34')===true, 'valid ipv4');
ok(P.isIPv4('999.1.1.1')===false, 'octet > 255 rejected');
ok(P.isIPv4('01.2.3.4')===false, 'leading zero rejected');
ok(P.isIPv4('1.2.3')===false, 'short ipv4 rejected');
ok(P.isIPv6('2001:db8::1')===true, 'valid ipv6');
ok(P.isIPv6('2001:db8::1::2')===false, 'double :: rejected');
ok(P.isIPv6('1.2.3.4')===false, 'ipv4 not ipv6');
ok(P.isHostname('example.com.')===true, 'trailing dot hostname ok');
ok(P.isHostname('')===false, 'empty hostname rejected');
ok(P.isHostname('a..b')===false, 'empty label rejected');
ok(P.parseTtl('1h')===3600, 'parse 1h');
ok(P.parseTtl('2d')===172800, 'parse 2d');
ok(P.parseTtl('300')===300, 'parse raw seconds');
ok(P.parseTtl('abc')===null, 'bad ttl null');
ok(P.formatTtl(3600)==='1h', 'format 1h');
ok(P.formatTtl(90)==='90s', 'format seconds when not round');
ok(P.formatTtl(604800)==='1w', 'format 1w');
var r=P.parseRecord('@ 3600 IN A 1.2.3.4');
ok(r.type==='A' && r.ttl===3600 && r.value==='1.2.3.4', 'parse full record');
ok(P.parseRecord('; comment')===null, 'comment skipped');
ok(P.parseRecord('@ IN A 1.2.3.4').ttl===null, 'ttl optional');
ok(P.parseRecord('@ 3600 IN ZZZZ x').error, 'unknown type errors');
ok(P.validateRecord(P.parseRecord('@ 3600 IN A 1.2.3.4')).valid===true, 'A record valid');
ok(P.validateRecord(P.parseRecord('@ 3600 IN A 999.1.1.1')).valid===false, 'bad A invalid');
ok(P.validateRecord(P.parseRecord('@ 3600 IN CNAME x.com.')).valid===false, 'root CNAME rejected');
ok(P.validateRecord(P.parseRecord('www 3600 IN CNAME x.com.')).valid===true, 'sub CNAME ok');
ok(P.validateRecord(P.parseRecord('@ 3600 IN MX 10 mail.x.com.')).valid===true, 'MX valid');
ok(P.validateRecord(P.parseRecord('@ 3600 IN MX mail.x.com.')).valid===false, 'MX missing priority');
ok(P.validateRecord(P.parseRecord('@ 3600 IN MX 10 1.2.3.4')).valid===false, 'MX to IP rejected');
ok(P.validateRecord(P.parseRecord('@ 10 IN A 1.2.3.4')).warnings.length>0, 'tiny TTL warns');
ok(P.validateRecord(P.parseRecord('_s._tcp 3600 IN SRV 10 60 5060 h.com.')).valid===true, 'SRV valid');
ok(P.validateRecord(P.parseRecord('@ 3600 IN SRV 10 60 99999 h.com.')).valid===false, 'SRV bad port');
var rows=P.parseZone('@ 3600 IN A 1.2.3.4\nwww 3600 IN CNAME example.com.\nwww 3600 IN A 1.2.3.4');
ok(rows.length===3, 'zone parses 3 rows');
ok(P.zoneSummary(rows).conflicts.length===1, 'CNAME + A conflict detected');
ok(P.zoneSummary(rows).byType.A===2, 'type counts');
var pe=P.propagationEstimate(3600);
ok(pe.worstCase===7200 && pe.humanWorst==='2h', 'propagation worst case');
console.log('DnsForge _test: '+n+' passed, 0 failed');
