
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const kernel=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1])[0];
const mo={exports:{}};new Function('module','exports',kernel)(mo,mo.exports);
const C=mo.exports;let pass=0,fail=0;
function ok(n,c){if(c)pass++;else{fail++;console.error('FAIL '+n);}}
ok('types', Object.keys(C.TYPES).length>=6);
ok('restarts', C.RESTARTS['on-failure'].length>0);
ok('no-exec', C.build({name:'a'}).error!=null);
ok('bad-name', C.build({name:'a b',execStart:'/x'}).error!=null);
var r=C.build({name:'myapp',execStart:'/usr/bin/myapp',user:'app',workdir:'/var/lib/app',
               description:'demo',type:'simple',restart:'on-failure',env:'A=1\nB=x y'});
ok('ok', !r.error);
var u=r.value.unit;
ok('sec-unit', u.indexOf('[Unit]')===0);
ok('desc', u.indexOf('Description=demo')>=0);
ok('after', u.indexOf('After=network-online.target')>=0);
ok('wants', u.indexOf('Wants=network-online.target')>=0);
ok('type', u.indexOf('Type=simple')>=0);
ok('user', u.indexOf('User=app')>=0);
ok('wd', u.indexOf('WorkingDirectory=/var/lib/app')>=0);
ok('env1', u.indexOf('Environment=A=1')>=0);
ok('env2', u.indexOf('Environment="B=x y"')>=0);
ok('exec', u.indexOf('ExecStart=/usr/bin/myapp')>=0);
ok('restart', u.indexOf('Restart=on-failure')>=0);
ok('restartsec', u.indexOf('RestartSec=5')>=0);
ok('harden', u.indexOf('NoNewPrivileges=yes')>=0&&u.indexOf('ProtectSystem=strict')>=0);
ok('rwpaths', u.indexOf('ReadWritePaths=/var/lib/app')>=0);
ok('install', u.indexOf('WantedBy=multi-user.target')>=0);
ok('fname', r.value.fileName==='myapp.service');
ok('cmds', r.value.cmds.length===5&&r.value.cmds[1].indexOf('daemon-reload')>=0);
var r2=C.build({name:'job',execStart:'/usr/bin/job',type:'oneshot',timer:true,onCalendar:'daily',user:'app'});
ok('oneshot-remain', r2.value.unit.indexOf('RemainAfterExit=yes')>=0);
ok('oneshot-norestart', r2.value.unit.indexOf('Restart=')<0);
ok('timer', r2.value.timer.indexOf('OnCalendar=daily')>=0);
ok('timer-persist', r2.value.timer.indexOf('Persistent=true')>=0);
ok('timer-wanted', r2.value.timer.indexOf('WantedBy=timers.target')>=0);
var r3=C.build({name:'x',execStart:'myapp'});
ok('warn-abs', r3.value.warn.join('|').indexOf('绝对路径')>=0);
ok('warn-root', r3.value.warn.join('|').indexOf('root')>=0);
var p=C.parseUnit('[Unit]\nDescription=a\n# c\n[Service]\nEnvironment=A=1\nEnvironment=B=2\n');
ok('parse-sec', p.order.join(',')==='Unit,Service');
ok('parse-multi', Array.isArray(p.sections.Service.Environment)&&p.sections.Service.Environment.length===2);
ok('parse-comment', p.sections.Unit.Description==='a');
ok('lint-empty', C.lint('').error!=null);
ok('lint-nosec', C.lint('hello world').error!=null);
function msgs(t){var x=C.lint(t);return x.value.issues.map(function(i){return i.msg;}).join('|');}
ok('lint-noservice', msgs('[Unit]\nDescription=a\n').indexOf('[Service]')>=0);
ok('lint-noexec', msgs('[Unit]\nDescription=a\n[Service]\nType=simple\n').indexOf('ExecStart')>=0);
ok('lint-relpath', msgs('[Unit]\nDescription=a\n[Service]\nExecStart=myapp\n').indexOf('绝对路径')>=0);
ok('lint-sudo', msgs('[Unit]\nDescription=a\n[Service]\nExecStart=/usr/bin/sudo /x\n').indexOf('sudo')>=0);
ok('lint-amp', msgs('[Unit]\nDescription=a\n[Service]\nExecStart=/x --serve &\n').indexOf('&')>=0);
ok('lint-shell', msgs('[Unit]\nDescription=a\n[Service]\nExecStart=/x | tee /y\n').indexOf('shell')>=0);
ok('lint-restart-bad', msgs('[Unit]\nDescription=a\n[Service]\nExecStart=/x\nRestart=alwyas\n').indexOf('非法的 Restart')>=0);
ok('lint-forking', msgs('[Unit]\nDescription=a\n[Service]\nType=forking\nExecStart=/x\n').indexOf('PIDFile')>=0);
ok('lint-oneshot', msgs('[Unit]\nDescription=a\n[Service]\nType=oneshot\nExecStart=/x\nRestart=always\n').indexOf('反复拉起')>=0);
ok('lint-root', msgs('[Unit]\nDescription=a\n[Service]\nExecStart=/x\nUser=root\n').indexOf('root')>=0);
ok('lint-envquote', msgs('[Unit]\nDescription=a\n[Service]\nExecStart=/x\nEnvironment=A=b c\n').indexOf('引号')>=0);
ok('lint-noinstall', msgs('[Unit]\nDescription=a\n[Service]\nExecStart=/x\n').indexOf('[Install]')>=0);
ok('lint-timer', msgs('[Unit]\nDescription=a\n[Timer]\nUnit=x.service\n[Install]\nWantedBy=timers.target\n').indexOf('触发条件')>=0);
ok('lint-envfile', msgs('[Unit]\nDescription=a\n[Service]\nExecStart=/x\nEnvironmentFile=/e\n').indexOf('EnvironmentFile')>=0);
var good=C.lint(r.value.unit);
ok('lint-good', good.value.stats.error===0);
ok('lint-score', good.value.score>=80);
console.log((fail?'FAIL':'PASS')+' SystemdForge '+pass+'/'+fail);process.exit(fail?1:0);
