
const fs=require('fs'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const kernel=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1])[0];
const mo={exports:{}};new Function('module','exports',kernel)(mo,mo.exports);
const C=mo.exports;let pass=0,fail=0;
function ok(n,c){if(c)pass++;else{fail++;console.error('FAIL '+n);}}
ok('pascal', C.pascal('user_name')==='UserName');
ok('pascal-num', C.pascal('2fa')==='N2Fa');
ok('key-plain', C.keyOf('abc')==='abc');
ok('key-quote', C.keyOf('a-b')==='"a-b"');
ok('smart-email', C.detectString('a@b.com',{smart:true})==='z.string().email()');
ok('smart-url', C.detectString('https://x.io',{smart:true})==='z.string().url()');
ok('smart-uuid', C.detectString('0f1a5c2e-9b3d-4c7a-8f21-6d5e4b3a2c10',{smart:true}).indexOf('uuid')>=0);
ok('smart-dt', C.detectString('2026-08-02T10:00:00Z',{smart:true}).indexOf('datetime')>=0);
ok('smart-date', C.detectString('2026-08-02',{smart:true}).indexOf('.date()')>=0);
ok('plain', C.detectString('a@b.com',{})==='z.string()');
ok('empty', C.toZod('').error!=null);
ok('badjson', C.toZod('{oops').error!=null);
ok('scalar', C.toZod('42').error!=null);
var r=C.toZod('{"a":1,"b":"x","c":true,"d":null}',{name:'Demo'});
ok('ok', !r.error);
var c=r.value.code;
ok('import', c.indexOf("import { z } from 'zod';")===0);
ok('varname', r.value.varName==='demoSchema');
ok('num', /a: z\.number\(\)/.test(c));
ok('str', /b: z\.string\(\)/.test(c));
ok('bool', /c: z\.boolean\(\)/.test(c));
ok('null', /d: z\.null\(\)/.test(c));
ok('infer', /export type Demo = z\.infer<typeof demoSchema>;/.test(c));
var r2=C.toZod('{"n":{"m":{"k":1}}}');
ok('nest', /n: z\.object\(\{/.test(r2.value.code));
ok('depth', r2.value.stats.depth===3);
var r3=C.toZod('{"list":[{"a":1},{"a":2,"b":"x"}]}');
ok('arr', /list: z\.array\(z\.object\(\{/.test(r3.value.code));
ok('arr-optional', /b: z\.string\(\)\.optional\(\)/.test(r3.value.code));
var r4=C.toZod('[{"a":1},{"a":null}]',{name:'Rows'});
ok('root-arr', /export const rowsSchema = z\.array\(/.test(r4.value.code));
ok('nullable', /\.nullable\(\)/.test(r4.value.code));
var r5=C.toZod('{"a":1}',{strict:true});
ok('strict', /\}\)\.strict\(\)/.test(r5.value.code));
var r6=C.toZod('{"a":1}',{importLine:false,inferType:false});
ok('bare', r6.value.code.indexOf('import')<0&&r6.value.code.indexOf('z.infer')<0);
var r7=C.toZod('{"a":1}',{intAsInt:true});
ok('int', /z\.number\(\)\.int\(\)/.test(r7.value.code));
var r8=C.toZod('{"a-b":1}');
ok('quoted-key', /"a-b": z\.number\(\)/.test(r8.value.code));
var r9=C.toZod('{"mix":[1,"x"]}');
ok('union', /z\.union\(\[/.test(r9.value.code));
var r10=C.toZod('{"e":{}}');
ok('empty-obj', /e: z\.object\(\{\}\)/.test(r10.value.code));
var r11=C.toZod('{"arr":[]}');
ok('empty-arr', /arr: z\.array\(z\.unknown\(\)\)/.test(r11.value.code));
ok('fields', C.toZod('{"a":1,"b":{"c":2}}').value.stats.fields===3);
ok('mergeAll-null', C.mergeAll([])===null);
console.log((fail?'FAIL':'PASS')+' ZodForge '+pass+'/'+fail);process.exit(fail?1:0);
